#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iEmpPower.Old_App_Code.iEmpPowerDAL.Working_Time
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paycompute_NewUIPRD")]
	public partial class leaverequestdalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public leaverequestdalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PayCompute20032020ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public leaverequestdalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public leaverequestdalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public leaverequestdalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public leaverequestdalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_Noofleaves")]
		public int sp_Get_Noofleaves([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGDA", DbType="Date")] System.Nullable<System.DateTime> bEGDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDDA", DbType="Date")] System.Nullable<System.DateTime> eNDDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(4)")] string aWART, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] ref System.Nullable<System.DateTime> firstday, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] ref System.Nullable<System.DateTime> lastday, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COUNT", DbType="Int")] ref System.Nullable<int> cOUNT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, bEGDA, eNDDA, aWART, firstday, lastday, cOUNT);
			firstday = ((System.Nullable<System.DateTime>)(result.GetParameterValue(4)));
			lastday = ((System.Nullable<System.DateTime>)(result.GetParameterValue(5)));
			cOUNT = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_update_leave_request", IsComposable=true)]
		public object sp_wt_update_leave_request(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> leave_req_id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGDA", DbType="Date")] System.Nullable<System.DateTime> bEGDA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDDA", DbType="Date")] System.Nullable<System.DateTime> eNDDA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGUZ", DbType="VarChar(8)")] string bEGUZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDUZ", DbType="VarChar(8)")] string eNDUZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(4)")] string aWART, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STDAZ", DbType="VarChar(8)")] string sTDAZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTE", DbType="VarChar(MAX)")] string nOTE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="APPROVED_BY", DbType="VarChar(10)")] string aPPROVED_BY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HRStatus", DbType="Bit")] ref System.Nullable<bool> hRStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Name", DbType="VarChar(100)")] ref string hR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Name", DbType="VarChar(100)")] ref string superVisor_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(100)")] ref string hR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Name", DbType="VarChar(100)")] ref string pERNR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Email", DbType="VarChar(100)")] ref string pERNR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Phn", DbType="VarChar(15)")] ref string hR_Phn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Phn", DbType="VarChar(15)")] ref string superVisor_Phn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), leave_req_id, pERNR, bEGDA, eNDDA, bEGUZ, eNDUZ, aWART, sTDAZ, nOTE, aPPROVED_BY, superVisorStatus, hRStatus, hR_Name, superVisor_Name, hR_Email, superVisor_Email, pERNR_Name, pERNR_Email, hR_Phn, superVisor_Phn);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(10)));
			hRStatus = ((System.Nullable<bool>)(result.GetParameterValue(11)));
			hR_Name = ((string)(result.GetParameterValue(12)));
			superVisor_Name = ((string)(result.GetParameterValue(13)));
			hR_Email = ((string)(result.GetParameterValue(14)));
			superVisor_Email = ((string)(result.GetParameterValue(15)));
			pERNR_Name = ((string)(result.GetParameterValue(16)));
			pERNR_Email = ((string)(result.GetParameterValue(17)));
			hR_Phn = ((string)(result.GetParameterValue(18)));
			superVisor_Phn = ((string)(result.GetParameterValue(19)));
			return ((object)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_delete_leave_req")]
		public int sp_wt_delete_leave_req([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> leave_req_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, leave_req_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_leave_validation")]
		public ISingleResult<sp_wt_leave_validationResult> sp_wt_leave_validation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGDA", DbType="Date")] System.Nullable<System.DateTime> bEGDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDDA", DbType="Date")] System.Nullable<System.DateTime> eNDDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(4)")] string aWART, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STDAZ", DbType="VarChar(8)")] string sTDAZ, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] ref System.Nullable<bool> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, bEGDA, eNDDA, aWART, sTDAZ, flag, status);
			status = ((System.Nullable<bool>)(result.GetParameterValue(6)));
			return ((ISingleResult<sp_wt_leave_validationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_Leaveinfo_mail")]
		public ISingleResult<sp_pi_get_Leaveinfo_mailResult> sp_pi_get_Leaveinfo_mail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pkey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string sts, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string tbltyp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pkey, iD, sts, tbltyp);
			return ((ISingleResult<sp_pi_get_Leaveinfo_mailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_team_calendar_leave_markings")]
		public ISingleResult<sp_wt_get_team_calendar_leave_markingsResult> sp_wt_get_team_calendar_leave_markings([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(8)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> first_date_of_month, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> last_date_of_month, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MngPernr", DbType="VarChar(8)")] string mngPernr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, first_date_of_month, last_date_of_month, mngPernr);
			return ((ISingleResult<sp_wt_get_team_calendar_leave_markingsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_calendar_leave_markings")]
		public ISingleResult<sp_wt_get_calendar_leave_markingsResult> sp_wt_get_calendar_leave_markings([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> from_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> to_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, from_date, to_date);
			return ((ISingleResult<sp_wt_get_calendar_leave_markingsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_DeleteLeaveinfo_mail")]
		public ISingleResult<sp_pi_get_DeleteLeaveinfo_mailResult> sp_pi_get_DeleteLeaveinfo_mail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pkey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sts, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string tbltyp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pkey, iD, sts, tbltyp);
			return ((ISingleResult<sp_pi_get_DeleteLeaveinfo_mailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_load_HolidayCalendar")]
		public ISingleResult<sp_load_HolidayCalendarResult> sp_load_HolidayCalendar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string year, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), year, compCode);
			return ((ISingleResult<sp_load_HolidayCalendarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_leave_validation_Prism")]
		public int sp_wt_leave_validation_Prism([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompCode", DbType="VarChar(20)")] string compCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGDA", DbType="Date")] System.Nullable<System.DateTime> bEGDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDDA", DbType="Date")] System.Nullable<System.DateTime> eNDDA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(4)")] string aWART, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGUZ", DbType="VarChar(8)")] string bEGUZ, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDUZ", DbType="VarChar(8)")] string eNDUZ, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STDAZ", DbType="VarChar(8)")] string sTDAZ, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HDType", DbType="Int")] System.Nullable<int> hDType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] ref System.Nullable<bool> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), compCode, pERNR, bEGDA, eNDDA, aWART, bEGUZ, eNDUZ, sTDAZ, flag, hDType, status);
			status = ((System.Nullable<bool>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_leave_overview")]
		public ISingleResult<sp_wt_get_leave_overviewResult> sp_wt_get_leave_overview([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compycode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Leave_Date_since", DbType="Date")] System.Nullable<System.DateTime> leave_Date_since, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rowcount", DbType="Int")] ref System.Nullable<int> rowcount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), compycode, pERNR, leave_Date_since, pageIndex, pageSize, flag, rowcount);
			rowcount = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((ISingleResult<sp_wt_get_leave_overviewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_calendar_leave_markings_forRWT")]
		public ISingleResult<sp_wt_get_calendar_leave_markings_forRWTResult> sp_wt_get_calendar_leave_markings_forRWT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ccode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> from_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> to_date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, ccode, from_date, to_date, type);
			return ((ISingleResult<sp_wt_get_calendar_leave_markings_forRWTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_individual_leave_detailsRWT")]
		public ISingleResult<sp_wt_get_individual_leave_detailsRWTResult> sp_wt_get_individual_leave_detailsRWT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ccode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SELECTED_DATE", DbType="Date")] System.Nullable<System.DateTime> sELECTED_DATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, ccode, sELECTED_DATE);
			return ((ISingleResult<sp_wt_get_individual_leave_detailsRWTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_leave_quota")]
		public ISingleResult<sp_wt_get_leave_quotaResult> sp_wt_get_leave_quota([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="VarChar(10)")] string yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, yEAR, compCode);
			return ((ISingleResult<sp_wt_get_leave_quotaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_individual_leave_details")]
		public ISingleResult<sp_wt_get_individual_leave_detailsResult> sp_wt_get_individual_leave_details([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compcode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), compcode, pERNR);
			return ((ISingleResult<sp_wt_get_individual_leave_detailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_leaveaddt_overviewmainsrch")]
		public ISingleResult<sp_wt_get_leaveaddt_overviewmainsrchResult> sp_wt_get_leaveaddt_overviewmainsrch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compycode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Leave_Date_since", DbType="Date")] System.Nullable<System.DateTime> leave_Date_since, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), compycode, pERNR, leave_Date_since, flag);
			return ((ISingleResult<sp_wt_get_leaveaddt_overviewmainsrchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_create_leave_request")]
		public int sp_wt_create_leave_request(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compcode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LEAVE_REQ_ID", DbType="Int")] System.Nullable<int> lEAVE_REQ_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PKEY", DbType="VarChar(50)")] string pKEY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGDA", DbType="Date")] System.Nullable<System.DateTime> bEGDA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDDA", DbType="Date")] System.Nullable<System.DateTime> eNDDA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGUZ", DbType="Time")] System.Nullable<System.TimeSpan> bEGUZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDUZ", DbType="Time")] System.Nullable<System.TimeSpan> eNDUZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(4)")] string aWART, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STDAZ", DbType="VarChar(8)")] string sTDAZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOTE", DbType="VarChar(MAX)")] string nOTE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Approver_pernr", DbType="VarChar(20)")] string approver_pernr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATUS", DbType="VarChar(100)")] string sTATUS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNAME", DbType="VarChar(100)")] string uNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TablTyp", DbType="VarChar(100)")] string tablTyp, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HDType", DbType="Int")] System.Nullable<int> hDType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(200)")] ref string hR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Supervisor_Email", DbType="VarChar(200)")] ref string supervisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Name", DbType="VarChar(200)")] ref string pERNR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Email", DbType="VarChar(200)")] ref string pERNR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LID", DbType="Int")] ref System.Nullable<int> lID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PKEYO", DbType="VarChar(50)")] ref string pKEYO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), compcode, lEAVE_REQ_ID, pKEY, pERNR, bEGDA, eNDDA, bEGUZ, eNDUZ, aWART, sTDAZ, nOTE, approver_pernr, sTATUS, uNAME, flag, tablTyp, hDType, hR_Email, supervisor_Email, pERNR_Name, pERNR_Email, lID, pKEYO);
			hR_Email = ((string)(result.GetParameterValue(17)));
			supervisor_Email = ((string)(result.GetParameterValue(18)));
			pERNR_Name = ((string)(result.GetParameterValue(19)));
			pERNR_Email = ((string)(result.GetParameterValue(20)));
			lID = ((System.Nullable<int>)(result.GetParameterValue(21)));
			pKEYO = ((string)(result.GetParameterValue(22)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ms_Load_ClockInOutReview_full")]
		public ISingleResult<sp_ms_Load_ClockInOutReview_fullResult> sp_ms_Load_ClockInOutReview_full([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pernr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROM_Date", DbType="Date")] System.Nullable<System.DateTime> fROM_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TO_Date", DbType="Date")] System.Nullable<System.DateTime> tO_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> rowdate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ccode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pernr, fROM_Date, tO_Date, rowdate, flag, ccode);
			return ((ISingleResult<sp_ms_Load_ClockInOutReview_fullResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ms_get_PunchInOutDetails_Rprt")]
		public ISingleResult<sp_ms_get_PunchInOutDetails_RprtResult> sp_ms_get_PunchInOutDetails_Rprt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ccode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pernr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MngPernr", DbType="VarChar(20)")] string mngPernr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> enddate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FLAG", DbType="Int")] System.Nullable<int> fLAG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WeekoffCOunt", DbType="Decimal(38,2)")] ref System.Nullable<decimal> weekoffCOunt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalDAys", DbType="Decimal(38,2)")] ref System.Nullable<decimal> totalDAys, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalHolidays", DbType="Decimal(38,2)")] ref System.Nullable<decimal> totalHolidays, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalWrkingDAys", DbType="Decimal(38,2)")] ref System.Nullable<decimal> totalWrkingDAys, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalHours", DbType="Decimal(38,2)")] ref System.Nullable<decimal> totalHours, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HrsDay", DbType="Decimal(38,2)")] ref System.Nullable<decimal> hrsDay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECCOUNT", DbType="Int")] ref System.Nullable<int> rECCOUNT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ccode, pernr, mngPernr, startDate, enddate, pageIndex, pageSize, fLAG, weekoffCOunt, totalDAys, totalHolidays, totalWrkingDAys, totalHours, hrsDay, rECCOUNT);
			weekoffCOunt = ((System.Nullable<decimal>)(result.GetParameterValue(8)));
			totalDAys = ((System.Nullable<decimal>)(result.GetParameterValue(9)));
			totalHolidays = ((System.Nullable<decimal>)(result.GetParameterValue(10)));
			totalWrkingDAys = ((System.Nullable<decimal>)(result.GetParameterValue(11)));
			totalHours = ((System.Nullable<decimal>)(result.GetParameterValue(12)));
			hrsDay = ((System.Nullable<decimal>)(result.GetParameterValue(13)));
			rECCOUNT = ((System.Nullable<int>)(result.GetParameterValue(14)));
			return ((ISingleResult<sp_ms_get_PunchInOutDetails_RprtResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ms_Load_ClockInOutReview_new")]
		public ISingleResult<sp_ms_Load_ClockInOutReview_newResult> sp_ms_Load_ClockInOutReview_new([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pernr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MngPernr", DbType="VarChar(10)")] string mngPernr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROM_Date", DbType="DateTime")] System.Nullable<System.DateTime> fROM_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TO_Date", DbType="DateTime")] System.Nullable<System.DateTime> tO_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ccode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pernr, mngPernr, fROM_Date, tO_Date, pageIndex, pageSize, flag, ccode);
			return ((ISingleResult<sp_ms_Load_ClockInOutReview_newResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_wt_leave_validationResult
	{
		
		private int _Column1;
		
		public sp_wt_leave_validationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_Leaveinfo_mailResult
	{
		
		private int _LEAVE_REQ_ID;
		
		private string _PKEY;
		
		private string _created_by;
		
		private string _empname;
		
		private System.Nullable<System.DateTime> _BEGDA;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private System.Nullable<System.TimeSpan> _BEGUZ;
		
		private System.Nullable<System.TimeSpan> _ENDUZ;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private string _STDAZ;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> _created_on;
		
		private string _approved_by;
		
		private string _mgrpnanme;
		
		private System.Nullable<System.DateTime> _approved_on;
		
		private string _approver_comments;
		
		private string _Duration;
		
		public sp_pi_get_Leaveinfo_mailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKEY", DbType="VarChar(50)")]
		public string PKEY
		{
			get
			{
				return this._PKEY;
			}
			set
			{
				if ((this._PKEY != value))
				{
					this._PKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empname", DbType="VarChar(81)")]
		public string empname
		{
			get
			{
				return this._empname;
			}
			set
			{
				if ((this._empname != value))
				{
					this._empname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date")]
		public System.Nullable<System.DateTime> BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> BEGUZ
		{
			get
			{
				return this._BEGUZ;
			}
			set
			{
				if ((this._BEGUZ != value))
				{
					this._BEGUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> ENDUZ
		{
			get
			{
				return this._ENDUZ;
			}
			set
			{
				if ((this._ENDUZ != value))
				{
					this._ENDUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDAZ", DbType="VarChar(8)")]
		public string STDAZ
		{
			get
			{
				return this._STDAZ;
			}
			set
			{
				if ((this._STDAZ != value))
				{
					this._STDAZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(MAX)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_on", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> created_on
		{
			get
			{
				return this._created_on;
			}
			set
			{
				if ((this._created_on != value))
				{
					this._created_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approved_by", DbType="VarChar(10)")]
		public string approved_by
		{
			get
			{
				return this._approved_by;
			}
			set
			{
				if ((this._approved_by != value))
				{
					this._approved_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgrpnanme", DbType="VarChar(81)")]
		public string mgrpnanme
		{
			get
			{
				return this._mgrpnanme;
			}
			set
			{
				if ((this._mgrpnanme != value))
				{
					this._mgrpnanme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approved_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> approved_on
		{
			get
			{
				return this._approved_on;
			}
			set
			{
				if ((this._approved_on != value))
				{
					this._approved_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approver_comments", DbType="VarChar(MAX)")]
		public string approver_comments
		{
			get
			{
				return this._approver_comments;
			}
			set
			{
				if ((this._approver_comments != value))
				{
					this._approver_comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="VarChar(100)")]
		public string Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_team_calendar_leave_markingsResult
	{
		
		private string _PERNR;
		
		private string _ENAME;
		
		private int _LEAVE_REQ_ID;
		
		private System.Nullable<System.DateTime> _DATUM;
		
		private string _STATUS;
		
		public sp_wt_get_team_calendar_leave_markingsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENAME", DbType="VarChar(50)")]
		public string ENAME
		{
			get
			{
				return this._ENAME;
			}
			set
			{
				if ((this._ENAME != value))
				{
					this._ENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATUM", DbType="Date")]
		public System.Nullable<System.DateTime> DATUM
		{
			get
			{
				return this._DATUM;
			}
			set
			{
				if ((this._DATUM != value))
				{
					this._DATUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(100)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_calendar_leave_markingsResult
	{
		
		private string _PERNR;
		
		private int _LEAVE_REQ_ID;
		
		private System.Nullable<System.DateTime> _BEGDA;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private System.Nullable<System.DateTime> _DATUM;
		
		private string _STATUS;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private string _STDAZ;
		
		private string _PKEY;
		
		private string _NOTE;
		
		private string _duration;
		
		private System.Nullable<System.TimeSpan> _BEGUZ;
		
		private System.Nullable<System.TimeSpan> _ENDUZ;
		
		public sp_wt_get_calendar_leave_markingsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date")]
		public System.Nullable<System.DateTime> BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATUM", DbType="Date")]
		public System.Nullable<System.DateTime> DATUM
		{
			get
			{
				return this._DATUM;
			}
			set
			{
				if ((this._DATUM != value))
				{
					this._DATUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(100)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDAZ", DbType="VarChar(8)")]
		public string STDAZ
		{
			get
			{
				return this._STDAZ;
			}
			set
			{
				if ((this._STDAZ != value))
				{
					this._STDAZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKEY", DbType="VarChar(50)")]
		public string PKEY
		{
			get
			{
				return this._PKEY;
			}
			set
			{
				if ((this._PKEY != value))
				{
					this._PKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(MAX)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(100)")]
		public string duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> BEGUZ
		{
			get
			{
				return this._BEGUZ;
			}
			set
			{
				if ((this._BEGUZ != value))
				{
					this._BEGUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> ENDUZ
		{
			get
			{
				return this._ENDUZ;
			}
			set
			{
				if ((this._ENDUZ != value))
				{
					this._ENDUZ = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_DeleteLeaveinfo_mailResult
	{
		
		private int _LEAVE_REQ_ID;
		
		private string _PKEY;
		
		private string _created_by;
		
		private string _empname;
		
		private System.Nullable<System.DateTime> _BEGDA;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private System.Nullable<System.TimeSpan> _BEGUZ;
		
		private System.Nullable<System.TimeSpan> _ENDUZ;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private string _STDAZ;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> _created_on;
		
		private string _approved_by;
		
		private string _mgrpnanme;
		
		private System.Nullable<System.DateTime> _approved_on;
		
		private string _approver_comments;
		
		private string _Duration;
		
		public sp_pi_get_DeleteLeaveinfo_mailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKEY", DbType="VarChar(50)")]
		public string PKEY
		{
			get
			{
				return this._PKEY;
			}
			set
			{
				if ((this._PKEY != value))
				{
					this._PKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empname", DbType="VarChar(81)")]
		public string empname
		{
			get
			{
				return this._empname;
			}
			set
			{
				if ((this._empname != value))
				{
					this._empname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date")]
		public System.Nullable<System.DateTime> BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> BEGUZ
		{
			get
			{
				return this._BEGUZ;
			}
			set
			{
				if ((this._BEGUZ != value))
				{
					this._BEGUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> ENDUZ
		{
			get
			{
				return this._ENDUZ;
			}
			set
			{
				if ((this._ENDUZ != value))
				{
					this._ENDUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDAZ", DbType="VarChar(8)")]
		public string STDAZ
		{
			get
			{
				return this._STDAZ;
			}
			set
			{
				if ((this._STDAZ != value))
				{
					this._STDAZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(MAX)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_on", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> created_on
		{
			get
			{
				return this._created_on;
			}
			set
			{
				if ((this._created_on != value))
				{
					this._created_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approved_by", DbType="VarChar(10)")]
		public string approved_by
		{
			get
			{
				return this._approved_by;
			}
			set
			{
				if ((this._approved_by != value))
				{
					this._approved_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgrpnanme", DbType="VarChar(81)")]
		public string mgrpnanme
		{
			get
			{
				return this._mgrpnanme;
			}
			set
			{
				if ((this._mgrpnanme != value))
				{
					this._mgrpnanme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approved_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> approved_on
		{
			get
			{
				return this._approved_on;
			}
			set
			{
				if ((this._approved_on != value))
				{
					this._approved_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approver_comments", DbType="VarChar(MAX)")]
		public string approver_comments
		{
			get
			{
				return this._approver_comments;
			}
			set
			{
				if ((this._approver_comments != value))
				{
					this._approver_comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="VarChar(100)")]
		public string Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
	}
	
	public partial class sp_load_HolidayCalendarResult
	{
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _holiday;
		
		private string _KLASSTXT;
		
		public sp_load_HolidayCalendarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_holiday", DbType="VarChar(100)")]
		public string holiday
		{
			get
			{
				return this._holiday;
			}
			set
			{
				if ((this._holiday != value))
				{
					this._holiday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KLASSTXT", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string KLASSTXT
		{
			get
			{
				return this._KLASSTXT;
			}
			set
			{
				if ((this._KLASSTXT != value))
				{
					this._KLASSTXT = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_leave_overviewResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private System.Nullable<int> _ID;
		
		private string _PERNR;
		
		private string _pkey;
		
		private System.Nullable<System.DateTime> _BEGDA;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private string _STATUS;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private System.Nullable<decimal> _TTL;
		
		private System.Nullable<System.DateTime> _CREATED_ON;
		
		private string _Ltype;
		
		private System.Nullable<System.TimeSpan> _BEGUZ;
		
		private System.Nullable<System.TimeSpan> _ENDUZ;
		
		public sp_wt_get_leave_overviewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkey", DbType="VarChar(60)")]
		public string pkey
		{
			get
			{
				return this._pkey;
			}
			set
			{
				if ((this._pkey != value))
				{
					this._pkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date")]
		public System.Nullable<System.DateTime> BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(30)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4)")]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(MAX)")]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTL", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> TTL
		{
			get
			{
				return this._TTL;
			}
			set
			{
				if ((this._TTL != value))
				{
					this._TTL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_ON
		{
			get
			{
				return this._CREATED_ON;
			}
			set
			{
				if ((this._CREATED_ON != value))
				{
					this._CREATED_ON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ltype", DbType="VarChar(30)")]
		public string Ltype
		{
			get
			{
				return this._Ltype;
			}
			set
			{
				if ((this._Ltype != value))
				{
					this._Ltype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> BEGUZ
		{
			get
			{
				return this._BEGUZ;
			}
			set
			{
				if ((this._BEGUZ != value))
				{
					this._BEGUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> ENDUZ
		{
			get
			{
				return this._ENDUZ;
			}
			set
			{
				if ((this._ENDUZ != value))
				{
					this._ENDUZ = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_calendar_leave_markings_forRWTResult
	{
		
		private string _PERNR;
		
		private int _LEAVE_REQ_ID;
		
		private System.Nullable<System.DateTime> _BEGDA;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private System.Nullable<System.DateTime> _DATUM;
		
		private string _STATUS;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private string _STDAZ;
		
		private string _PKEY;
		
		private string _NOTE;
		
		private string _STDAZ1;
		
		private string _duration;
		
		public sp_wt_get_calendar_leave_markings_forRWTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(20)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date")]
		public System.Nullable<System.DateTime> BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATUM", DbType="Date")]
		public System.Nullable<System.DateTime> DATUM
		{
			get
			{
				return this._DATUM;
			}
			set
			{
				if ((this._DATUM != value))
				{
					this._DATUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(100)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDAZ", DbType="VarChar(8)")]
		public string STDAZ
		{
			get
			{
				return this._STDAZ;
			}
			set
			{
				if ((this._STDAZ != value))
				{
					this._STDAZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKEY", DbType="VarChar(50)")]
		public string PKEY
		{
			get
			{
				return this._PKEY;
			}
			set
			{
				if ((this._PKEY != value))
				{
					this._PKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(MAX)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDAZ1", DbType="VarChar(8)")]
		public string STDAZ1
		{
			get
			{
				return this._STDAZ1;
			}
			set
			{
				if ((this._STDAZ1 != value))
				{
					this._STDAZ1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(100)")]
		public string duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_individual_leave_detailsRWTResult
	{
		
		private int _LEAVE_REQ_ID;
		
		private string _PERNR;
		
		private string _BEGDA;
		
		private string _ENDDA;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private string _STATUS;
		
		private System.Nullable<decimal> _Ttl;
		
		private string _TABLE_TYPE;
		
		public sp_wt_get_individual_leave_detailsRWTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(20)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="VarChar(20)")]
		public string BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="VarChar(20)")]
		public string ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(100)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttl", DbType="Decimal(11,1)")]
		public System.Nullable<decimal> Ttl
		{
			get
			{
				return this._Ttl;
			}
			set
			{
				if ((this._Ttl != value))
				{
					this._Ttl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_TYPE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TABLE_TYPE
		{
			get
			{
				return this._TABLE_TYPE;
			}
			set
			{
				if ((this._TABLE_TYPE != value))
				{
					this._TABLE_TYPE = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_leave_quotaResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private System.DateTime _DESTA;
		
		private System.DateTime _DEEND;
		
		private decimal _ANZHL;
		
		private decimal _KVERB;
		
		private System.Nullable<decimal> _available;
		
		private string _KTEXT;
		
		public sp_wt_get_leave_quotaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESTA", DbType="Date NOT NULL")]
		public System.DateTime DESTA
		{
			get
			{
				return this._DESTA;
			}
			set
			{
				if ((this._DESTA != value))
				{
					this._DESTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEEND", DbType="Date NOT NULL")]
		public System.DateTime DEEND
		{
			get
			{
				return this._DEEND;
			}
			set
			{
				if ((this._DEEND != value))
				{
					this._DEEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANZHL", DbType="Decimal(10,1) NOT NULL")]
		public decimal ANZHL
		{
			get
			{
				return this._ANZHL;
			}
			set
			{
				if ((this._ANZHL != value))
				{
					this._ANZHL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KVERB", DbType="Decimal(10,1) NOT NULL")]
		public decimal KVERB
		{
			get
			{
				return this._KVERB;
			}
			set
			{
				if ((this._KVERB != value))
				{
					this._KVERB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_available", DbType="Decimal(11,1)")]
		public System.Nullable<decimal> available
		{
			get
			{
				return this._available;
			}
			set
			{
				if ((this._available != value))
				{
					this._available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string KTEXT
		{
			get
			{
				return this._KTEXT;
			}
			set
			{
				if ((this._KTEXT != value))
				{
					this._KTEXT = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_individual_leave_detailsResult
	{
		
		private int _LEAVE_REQ_ID;
		
		private string _PERNR;
		
		private string _BEGDA;
		
		private string _ENDDA;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private string _STATUS;
		
		private System.Nullable<decimal> _Ttl;
		
		private string _TABLE_TYPE;
		
		private System.Nullable<System.TimeSpan> _BEGUZ;
		
		private System.Nullable<System.TimeSpan> _ENDUZ;
		
		public sp_wt_get_individual_leave_detailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVE_REQ_ID", DbType="Int NOT NULL")]
		public int LEAVE_REQ_ID
		{
			get
			{
				return this._LEAVE_REQ_ID;
			}
			set
			{
				if ((this._LEAVE_REQ_ID != value))
				{
					this._LEAVE_REQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(20)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="VarChar(20)")]
		public string BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="VarChar(20)")]
		public string ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(100)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttl", DbType="Decimal(11,1)")]
		public System.Nullable<decimal> Ttl
		{
			get
			{
				return this._Ttl;
			}
			set
			{
				if ((this._Ttl != value))
				{
					this._Ttl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_TYPE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TABLE_TYPE
		{
			get
			{
				return this._TABLE_TYPE;
			}
			set
			{
				if ((this._TABLE_TYPE != value))
				{
					this._TABLE_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> BEGUZ
		{
			get
			{
				return this._BEGUZ;
			}
			set
			{
				if ((this._BEGUZ != value))
				{
					this._BEGUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> ENDUZ
		{
			get
			{
				return this._ENDUZ;
			}
			set
			{
				if ((this._ENDUZ != value))
				{
					this._ENDUZ = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_leaveaddt_overviewmainsrchResult
	{
		
		private System.Nullable<int> _ID;
		
		private string _PERNR;
		
		private string _pkey;
		
		private System.Nullable<System.DateTime> _BEGDA;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private string _STATUS;
		
		private string _AWART;
		
		private string _ATEXT;
		
		private System.Nullable<decimal> _TTL;
		
		private System.Nullable<System.DateTime> _CREATED_ON;
		
		private string _Ltype;
		
		private System.Nullable<System.TimeSpan> _BEGUZ;
		
		private System.Nullable<System.TimeSpan> _ENDUZ;
		
		public sp_wt_get_leaveaddt_overviewmainsrchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(20)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkey", DbType="VarChar(60)")]
		public string pkey
		{
			get
			{
				return this._pkey;
			}
			set
			{
				if ((this._pkey != value))
				{
					this._pkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date")]
		public System.Nullable<System.DateTime> BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this._BEGDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(30)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(4)")]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATEXT", DbType="VarChar(MAX)")]
		public string ATEXT
		{
			get
			{
				return this._ATEXT;
			}
			set
			{
				if ((this._ATEXT != value))
				{
					this._ATEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTL", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> TTL
		{
			get
			{
				return this._TTL;
			}
			set
			{
				if ((this._TTL != value))
				{
					this._TTL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_ON
		{
			get
			{
				return this._CREATED_ON;
			}
			set
			{
				if ((this._CREATED_ON != value))
				{
					this._CREATED_ON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ltype", DbType="VarChar(30)")]
		public string Ltype
		{
			get
			{
				return this._Ltype;
			}
			set
			{
				if ((this._Ltype != value))
				{
					this._Ltype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> BEGUZ
		{
			get
			{
				return this._BEGUZ;
			}
			set
			{
				if ((this._BEGUZ != value))
				{
					this._BEGUZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDUZ", DbType="Time")]
		public System.Nullable<System.TimeSpan> ENDUZ
		{
			get
			{
				return this._ENDUZ;
			}
			set
			{
				if ((this._ENDUZ != value))
				{
					this._ENDUZ = value;
				}
			}
		}
	}
	
	public partial class sp_ms_Load_ClockInOutReview_fullResult
	{
		
		private System.Nullable<int> _InID;
		
		private System.Nullable<System.DateTime> _dt;
		
		private string _Punch_In;
		
		private System.Nullable<int> _OUT_ID;
		
		private string _Punch_Out;
		
		private string _Total_No_of_Hours;
		
		public sp_ms_Load_ClockInOutReview_fullResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InID", DbType="Int")]
		public System.Nullable<int> InID
		{
			get
			{
				return this._InID;
			}
			set
			{
				if ((this._InID != value))
				{
					this._InID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="Date")]
		public System.Nullable<System.DateTime> dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this._dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Punch_In", DbType="VarChar(MAX)")]
		public string Punch_In
		{
			get
			{
				return this._Punch_In;
			}
			set
			{
				if ((this._Punch_In != value))
				{
					this._Punch_In = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUT_ID", DbType="Int")]
		public System.Nullable<int> OUT_ID
		{
			get
			{
				return this._OUT_ID;
			}
			set
			{
				if ((this._OUT_ID != value))
				{
					this._OUT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Punch_Out", DbType="VarChar(MAX)")]
		public string Punch_Out
		{
			get
			{
				return this._Punch_Out;
			}
			set
			{
				if ((this._Punch_Out != value))
				{
					this._Punch_Out = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total No of Hours]", Storage="_Total_No_of_Hours", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Total_No_of_Hours
		{
			get
			{
				return this._Total_No_of_Hours;
			}
			set
			{
				if ((this._Total_No_of_Hours != value))
				{
					this._Total_No_of_Hours = value;
				}
			}
		}
	}
	
	public partial class sp_ms_get_PunchInOutDetails_RprtResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private string _EmpPernnr;
		
		private string _ENAME;
		
		private System.Nullable<decimal> _Tworkingdays;
		
		private System.Nullable<decimal> _totalhrs;
		
		private System.Nullable<decimal> _tolhrsbyemp;
		
		private System.Nullable<decimal> _avgavailability;
		
		private System.Nullable<decimal> _Leavecountd;
		
		private System.Nullable<decimal> _ReqAttendanceCount;
		
		private System.Nullable<decimal> _MissedPunch;
		
		private System.Nullable<System.DateTime> _DateofJoining;
		
		public sp_ms_get_PunchInOutDetails_RprtResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpPernnr", DbType="VarChar(MAX)")]
		public string EmpPernnr
		{
			get
			{
				return this._EmpPernnr;
			}
			set
			{
				if ((this._EmpPernnr != value))
				{
					this._EmpPernnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENAME", DbType="VarChar(MAX)")]
		public string ENAME
		{
			get
			{
				return this._ENAME;
			}
			set
			{
				if ((this._ENAME != value))
				{
					this._ENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tworkingdays", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Tworkingdays
		{
			get
			{
				return this._Tworkingdays;
			}
			set
			{
				if ((this._Tworkingdays != value))
				{
					this._Tworkingdays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalhrs", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> totalhrs
		{
			get
			{
				return this._totalhrs;
			}
			set
			{
				if ((this._totalhrs != value))
				{
					this._totalhrs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tolhrsbyemp", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> tolhrsbyemp
		{
			get
			{
				return this._tolhrsbyemp;
			}
			set
			{
				if ((this._tolhrsbyemp != value))
				{
					this._tolhrsbyemp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avgavailability", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> avgavailability
		{
			get
			{
				return this._avgavailability;
			}
			set
			{
				if ((this._avgavailability != value))
				{
					this._avgavailability = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leavecountd", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Leavecountd
		{
			get
			{
				return this._Leavecountd;
			}
			set
			{
				if ((this._Leavecountd != value))
				{
					this._Leavecountd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReqAttendanceCount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ReqAttendanceCount
		{
			get
			{
				return this._ReqAttendanceCount;
			}
			set
			{
				if ((this._ReqAttendanceCount != value))
				{
					this._ReqAttendanceCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MissedPunch", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> MissedPunch
		{
			get
			{
				return this._MissedPunch;
			}
			set
			{
				if ((this._MissedPunch != value))
				{
					this._MissedPunch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateofJoining", DbType="Date")]
		public System.Nullable<System.DateTime> DateofJoining
		{
			get
			{
				return this._DateofJoining;
			}
			set
			{
				if ((this._DateofJoining != value))
				{
					this._DateofJoining = value;
				}
			}
		}
	}
	
	public partial class sp_ms_Load_ClockInOutReview_newResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private System.Nullable<System.DateTime> _DATES;
		
		private string _DATES1;
		
		private string _DAY;
		
		private string _PERNR;
		
		private string _Punch_In;
		
		private string _Punch_Out;
		
		private string _Total_No_of_Hours;
		
		private string _Total_Break_Hours;
		
		private System.Nullable<bool> _count;
		
		private string _STATUS;
		
		private string _TXT_LONG;
		
		private System.Nullable<int> _TtlDays;
		
		private System.Nullable<int> _RecordCnt;
		
		public sp_ms_Load_ClockInOutReview_newResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATES", DbType="Date")]
		public System.Nullable<System.DateTime> DATES
		{
			get
			{
				return this._DATES;
			}
			set
			{
				if ((this._DATES != value))
				{
					this._DATES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATES1", DbType="VarChar(MAX)")]
		public string DATES1
		{
			get
			{
				return this._DATES1;
			}
			set
			{
				if ((this._DATES1 != value))
				{
					this._DATES1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAY", DbType="VarChar(MAX)")]
		public string DAY
		{
			get
			{
				return this._DAY;
			}
			set
			{
				if ((this._DAY != value))
				{
					this._DAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(MAX)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Punch In]", Storage="_Punch_In", DbType="VarChar(MAX)")]
		public string Punch_In
		{
			get
			{
				return this._Punch_In;
			}
			set
			{
				if ((this._Punch_In != value))
				{
					this._Punch_In = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Punch Out]", Storage="_Punch_Out", DbType="VarChar(MAX)")]
		public string Punch_Out
		{
			get
			{
				return this._Punch_Out;
			}
			set
			{
				if ((this._Punch_Out != value))
				{
					this._Punch_Out = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total No of Hours]", Storage="_Total_No_of_Hours", DbType="VarChar(MAX)")]
		public string Total_No_of_Hours
		{
			get
			{
				return this._Total_No_of_Hours;
			}
			set
			{
				if ((this._Total_No_of_Hours != value))
				{
					this._Total_No_of_Hours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Total Break Hours]", Storage="_Total_Break_Hours", DbType="VarChar(MAX)")]
		public string Total_Break_Hours
		{
			get
			{
				return this._Total_Break_Hours;
			}
			set
			{
				if ((this._Total_Break_Hours != value))
				{
					this._Total_Break_Hours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Bit")]
		public System.Nullable<bool> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(MAX)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TXT_LONG", DbType="VarChar(MAX)")]
		public string TXT_LONG
		{
			get
			{
				return this._TXT_LONG;
			}
			set
			{
				if ((this._TXT_LONG != value))
				{
					this._TXT_LONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TtlDays", DbType="Int")]
		public System.Nullable<int> TtlDays
		{
			get
			{
				return this._TtlDays;
			}
			set
			{
				if ((this._TtlDays != value))
				{
					this._TtlDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCnt", DbType="Int")]
		public System.Nullable<int> RecordCnt
		{
			get
			{
				return this._RecordCnt;
			}
			set
			{
				if ((this._RecordCnt != value))
				{
					this._RecordCnt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
