<?xml version="1.0" encoding="utf-8"?><Database Name="iEmpPower" Class="wtpayslipDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=iEmpPower;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iEmpPowerConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_wt_load_form16" Method="sp_wt_load_form16">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="year" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_wt_load_form16Result">
      <Column Name="PERNR" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="form16" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_wt_load_claim_stmt" Method="sp_wt_load_claim_stmt">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="year" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="month" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_wt_load_claim_stmtResult">
      <Column Name="PERNR" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Statement" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_wt_load_timestatement" Method="sp_wt_load_timestatement">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="year" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="month" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_wt_load_timestatementResult">
      <Column Name="PERNR" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="month" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="timestatement" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_wt_load_payslip" Method="sp_wt_load_payslip">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="year" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="month" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_wt_load_payslipResult">
      <Column Name="PERNR" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="month" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="payslip_content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>