#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iEmpPower.Old_App_Code.iEmpPowerDAL.Working_Time
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paycompute_NewUIPRD")]
	public partial class wtrecordworkingtimedalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public wtrecordworkingtimedalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PayCompute20032020ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public wtrecordworkingtimedalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public wtrecordworkingtimedalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public wtrecordworkingtimedalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public wtrecordworkingtimedalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_load_working_hours_for_employee")]
		public ISingleResult<sp_wt_load_working_hours_for_employeeResult> sp_wt_load_working_hours_for_employee([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_wt_load_working_hours_for_employeeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Assigntask_SubEmp")]
		public ISingleResult<sp_Assigntask_SubEmpResult> sp_Assigntask_SubEmp([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MNGRPERNR", DbType="VarChar(8)")] string mNGRPERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(8)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="Date")] System.Nullable<System.DateTime> fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="Date")] System.Nullable<System.DateTime> tODATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mNGRPERNR, pERNR, fROMDATE, tODATE);
			return ((ISingleResult<sp_Assigntask_SubEmpResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getEmpAssigndtask")]
		public ISingleResult<sp_getEmpAssigndtaskResult> sp_getEmpAssigndtask([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(8)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="Date")] System.Nullable<System.DateTime> fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="Date")] System.Nullable<System.DateTime> tODATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, fROMDATE, tODATE);
			return ((ISingleResult<sp_getEmpAssigndtaskResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loadAssigntask_tocalendar")]
		public ISingleResult<sp_loadAssigntask_tocalendarResult> sp_loadAssigntask_tocalendar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MNGRPERNR", DbType="VarChar(10)")] string mNGRPERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mNGRPERNR, from, to);
			return ((ISingleResult<sp_loadAssigntask_tocalendarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_loadEmpAssigntask_tocalendar")]
		public ISingleResult<sp_loadEmpAssigntask_tocalendarResult> sp_loadEmpAssigntask_tocalendar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMPPERNR", DbType="VarChar(10)")] string eMPPERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eMPPERNR, from, to);
			return ((ISingleResult<sp_loadEmpAssigntask_tocalendarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_create_AssignTaskActivities")]
		public int sp_wt_create_AssignTaskActivities([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKID", DbType="BigInt")] System.Nullable<long> tASKID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVITYID", DbType="VarChar(MAX)")] string aCTIVITYID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKWORKDATE", DbType="VarChar(MAX)")] string tASKWORKDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKWORK", DbType="VarChar(MAX)")] string tASKWORK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKHOURS", DbType="VarChar(MAX)")] string tASKHOURS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATEDONDATE", DbType="Date")] System.Nullable<System.DateTime> cREATEDONDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATED_BYPERN", DbType="VarChar(MAX)")] string cREATED_BYPERN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MNGRUPDATEDON", DbType="Date")] System.Nullable<System.DateTime> mNGRUPDATEDON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MNGRUPDATEDBY", DbType="VarChar(MAX)")] string mNGRUPDATEDBY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMPUPDATEON", DbType="Date")] System.Nullable<System.DateTime> eMPUPDATEON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMPUPDATEDBY", DbType="VarChar(MAX)")] string eMPUPDATEDBY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKSTATUS", DbType="VarChar(MAX)")] string tASKSTATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FLAG", DbType="Int")] System.Nullable<int> fLAG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tASKID, pERNR, aCTIVITYID, tASKWORKDATE, tASKWORK, tASKHOURS, cREATEDONDATE, cREATED_BYPERN, mNGRUPDATEDON, mNGRUPDATEDBY, eMPUPDATEON, eMPUPDATEDBY, tASKSTATUS, fLAG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_create_ActualTaskHour")]
		public int sp_wt_create_ActualTaskHour([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKID", DbType="BigInt")] System.Nullable<long> tASKID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKWORKDATE", DbType="VarChar(MAX)")] string tASKWORKDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASKHOURS", DbType="VarChar(MAX)")] string tASKHOURS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATEDONDATE", DbType="Date")] System.Nullable<System.DateTime> cREATEDONDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CREATED_BYPERN", DbType="VarChar(MAX)")] string cREATED_BYPERN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MNGRUPDATEDON", DbType="Date")] System.Nullable<System.DateTime> mNGRUPDATEDON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MNGRUPDATEDBY", DbType="VarChar(MAX)")] string mNGRUPDATEDBY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMPUPDATEON", DbType="Date")] System.Nullable<System.DateTime> eMPUPDATEON, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMPUPDATEDBY", DbType="VarChar(MAX)")] string eMPUPDATEDBY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tASKID, pERNR, tASKWORKDATE, tASKHOURS, cREATEDONDATE, cREATED_BYPERN, mNGRUPDATEDON, mNGRUPDATEDBY, eMPUPDATEON, eMPUPDATEDBY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Load_PlannedActivities")]
		public ISingleResult<sp_Load_PlannedActivitiesResult> sp_Load_PlannedActivities([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(50)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MngPernr", DbType="VarChar(8)")] string mngPernr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, fromDate, toDate, mngPernr);
			return ((ISingleResult<sp_Load_PlannedActivitiesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_recordworking_time_date")]
		public ISingleResult<sp_wt_get_recordworking_time_dateResult> sp_wt_get_recordworking_time_date([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pkey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ccode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pkey, ccode);
			return ((ISingleResult<sp_wt_get_recordworking_time_dateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_recordworking_time")]
		public ISingleResult<sp_wt_get_recordworking_timeResult> sp_wt_get_recordworking_time([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pernr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pernr, compcode, from, to);
			return ((ISingleResult<sp_wt_get_recordworking_timeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_recordworking_time_week")]
		public ISingleResult<sp_wt_get_recordworking_time_weekResult> sp_wt_get_recordworking_time_week([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pernr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string compcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pernr, compcode, from, to);
			return ((ISingleResult<sp_wt_get_recordworking_time_weekResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_get_recordworking_time_Mail")]
		public ISingleResult<sp_wt_get_recordworking_time_MailResult> sp_wt_get_recordworking_time_Mail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pkey", DbType="VarChar(MAX)")] string pkey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ccode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupervisorMail", DbType="VarChar(MAX)")] ref string supervisorMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpMail", DbType="VarChar(MAX)")] ref string empMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpName", DbType="VarChar(MAX)")] ref string empName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupervisiorName", DbType="VarChar(MAX)")] ref string supervisiorName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpId", DbType="VarChar(8)")] ref string empId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pkey, ccode, supervisorMail, empMail, empName, supervisiorName, empId);
			supervisorMail = ((string)(result.GetParameterValue(2)));
			empMail = ((string)(result.GetParameterValue(3)));
			empName = ((string)(result.GetParameterValue(4)));
			supervisiorName = ((string)(result.GetParameterValue(5)));
			empId = ((string)(result.GetParameterValue(6)));
			return ((ISingleResult<sp_wt_get_recordworking_time_MailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_update_recordworking_time")]
		public int sp_wt_update_recordworking_time(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CURRECORDNO", DbType="VarChar(MAX)")] string cURRECORDNO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(MAX)")] string aWART, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATSHOURS", DbType="VarChar(MAX)")] string cATSHOURS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WORKINGDATE", DbType="VarChar(MAX)")] string wORKINGDATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string costcenter, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string order, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RPROJ", DbType="VarChar(MAX)")] string rPROJ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNPLNR", DbType="VarChar(MAX)")] string rNPLNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LSTAR", DbType="VarChar(MAX)")] string lSTAR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RREMARKS", DbType="VarChar(MAX)")] string rREMARKS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TicketIDS", DbType="VarChar(MAX)")] string ticketIDS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Plndhrs", DbType="VarChar(MAX)")] string plndhrs, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string company_Code, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Name", DbType="VarChar(100)")] ref string superVisor_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Name", DbType="VarChar(100)")] ref string pERNR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Email", DbType="VarChar(100)")] ref string pERNR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] ref string errormessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cURRECORDNO, pERNR, aWART, cATSHOURS, wORKINGDATE, costcenter, order, rPROJ, rNPLNR, lSTAR, rREMARKS, ticketIDS, plndhrs, company_Code, superVisorStatus, superVisor_Name, superVisor_Email, pERNR_Name, pERNR_Email, errormessage);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(14)));
			superVisor_Name = ((string)(result.GetParameterValue(15)));
			superVisor_Email = ((string)(result.GetParameterValue(16)));
			pERNR_Name = ((string)(result.GetParameterValue(17)));
			pERNR_Email = ((string)(result.GetParameterValue(18)));
			errormessage = ((string)(result.GetParameterValue(19)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_wt_create_recordworking_time")]
		public int sp_wt_create_recordworking_time(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AWART", DbType="VarChar(MAX)")] string aWART, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATSHOURS", DbType="VarChar(MAX)")] string cATSHOURS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WORKINGDATE", DbType="VarChar(MAX)")] string wORKINGDATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string costcenter, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string order, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RPROJ", DbType="VarChar(MAX)")] string rPROJ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNPLNR", DbType="VarChar(MAX)")] string rNPLNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LSTAR", DbType="VarChar(MAX)")] string lSTAR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RREMARKS", DbType="VarChar(MAX)")] string rREMARKS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TicketIDS", DbType="VarChar(MAX)")] string ticketIDS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Plndhrs", DbType="VarChar(MAX)")] string plndhrs, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string company_Code, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Name", DbType="VarChar(100)")] ref string superVisor_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Name", DbType="VarChar(100)")] ref string pERNR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Email", DbType="VarChar(100)")] ref string pERNR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] ref string errormessage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] ref string pkey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, aWART, cATSHOURS, wORKINGDATE, costcenter, order, rPROJ, rNPLNR, lSTAR, rREMARKS, ticketIDS, plndhrs, company_Code, superVisorStatus, superVisor_Name, superVisor_Email, pERNR_Name, pERNR_Email, errormessage, pkey);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(13)));
			superVisor_Name = ((string)(result.GetParameterValue(14)));
			superVisor_Email = ((string)(result.GetParameterValue(15)));
			pERNR_Name = ((string)(result.GetParameterValue(16)));
			pERNR_Email = ((string)(result.GetParameterValue(17)));
			errormessage = ((string)(result.GetParameterValue(18)));
			pkey = ((string)(result.GetParameterValue(19)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_wt_load_working_hours_for_employeeResult
	{
		
		private string _PERNR;
		
		private System.Nullable<decimal> _ARBST;
		
		public sp_wt_load_working_hours_for_employeeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARBST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> ARBST
		{
			get
			{
				return this._ARBST;
			}
			set
			{
				if ((this._ARBST != value))
				{
					this._ARBST = value;
				}
			}
		}
	}
	
	public partial class sp_Assigntask_SubEmpResult
	{
		
		private string _PERNR;
		
		private string _ACTIVITYID;
		
		private System.Nullable<System.DateTime> _Monday;
		
		private System.Nullable<System.DateTime> _Tuesday;
		
		private System.Nullable<System.DateTime> _Wednesday;
		
		private System.Nullable<System.DateTime> _Thursday;
		
		private System.Nullable<System.DateTime> _Friday;
		
		private string _MondayTask;
		
		private string _TuesdayTask;
		
		private string _WednesdayTask;
		
		private string _ThursdayTask;
		
		private string _FridayTask;
		
		private string _MondayHours;
		
		private string _TuesdayHours;
		
		private string _WednesdayHours;
		
		private string _ThursdayHours;
		
		private string _FridayHours;
		
		public sp_Assigntask_SubEmpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVITYID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ACTIVITYID
		{
			get
			{
				return this._ACTIVITYID;
			}
			set
			{
				if ((this._ACTIVITYID != value))
				{
					this._ACTIVITYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Date")]
		public System.Nullable<System.DateTime> Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this._Monday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="Date")]
		public System.Nullable<System.DateTime> Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this._Tuesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="Date")]
		public System.Nullable<System.DateTime> Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this._Wednesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="Date")]
		public System.Nullable<System.DateTime> Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this._Thursday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Date")]
		public System.Nullable<System.DateTime> Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this._Friday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayTask", DbType="VarChar(MAX)")]
		public string MondayTask
		{
			get
			{
				return this._MondayTask;
			}
			set
			{
				if ((this._MondayTask != value))
				{
					this._MondayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayTask", DbType="VarChar(MAX)")]
		public string TuesdayTask
		{
			get
			{
				return this._TuesdayTask;
			}
			set
			{
				if ((this._TuesdayTask != value))
				{
					this._TuesdayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayTask", DbType="VarChar(MAX)")]
		public string WednesdayTask
		{
			get
			{
				return this._WednesdayTask;
			}
			set
			{
				if ((this._WednesdayTask != value))
				{
					this._WednesdayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayTask", DbType="VarChar(MAX)")]
		public string ThursdayTask
		{
			get
			{
				return this._ThursdayTask;
			}
			set
			{
				if ((this._ThursdayTask != value))
				{
					this._ThursdayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayTask", DbType="VarChar(MAX)")]
		public string FridayTask
		{
			get
			{
				return this._FridayTask;
			}
			set
			{
				if ((this._FridayTask != value))
				{
					this._FridayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayHours", DbType="VarChar(20)")]
		public string MondayHours
		{
			get
			{
				return this._MondayHours;
			}
			set
			{
				if ((this._MondayHours != value))
				{
					this._MondayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayHours", DbType="VarChar(20)")]
		public string TuesdayHours
		{
			get
			{
				return this._TuesdayHours;
			}
			set
			{
				if ((this._TuesdayHours != value))
				{
					this._TuesdayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayHours", DbType="VarChar(20)")]
		public string WednesdayHours
		{
			get
			{
				return this._WednesdayHours;
			}
			set
			{
				if ((this._WednesdayHours != value))
				{
					this._WednesdayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayHours", DbType="VarChar(20)")]
		public string ThursdayHours
		{
			get
			{
				return this._ThursdayHours;
			}
			set
			{
				if ((this._ThursdayHours != value))
				{
					this._ThursdayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayHours", DbType="VarChar(20)")]
		public string FridayHours
		{
			get
			{
				return this._FridayHours;
			}
			set
			{
				if ((this._FridayHours != value))
				{
					this._FridayHours = value;
				}
			}
		}
	}
	
	public partial class sp_getEmpAssigndtaskResult
	{
		
		private string _PERNR;
		
		private string _ACTIVITYID;
		
		private string _AWART;
		
		private System.Nullable<System.DateTime> _Monday;
		
		private System.Nullable<System.DateTime> _Tuesday;
		
		private System.Nullable<System.DateTime> _Wednesday;
		
		private System.Nullable<System.DateTime> _Thursday;
		
		private System.Nullable<System.DateTime> _Friday;
		
		private string _MondayTask;
		
		private string _TuesdayTask;
		
		private string _WednesdayTask;
		
		private string _ThursdayTask;
		
		private string _FridayTask;
		
		private string _MondayHours;
		
		private string _TuesdayHours;
		
		private string _WednesdayHours;
		
		private string _ThursdayHours;
		
		private string _FridayHours;
		
		public sp_getEmpAssigndtaskResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVITYID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ACTIVITYID
		{
			get
			{
				return this._ACTIVITYID;
			}
			set
			{
				if ((this._ACTIVITYID != value))
				{
					this._ACTIVITYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(100)")]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Date")]
		public System.Nullable<System.DateTime> Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this._Monday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="Date")]
		public System.Nullable<System.DateTime> Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this._Tuesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="Date")]
		public System.Nullable<System.DateTime> Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this._Wednesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="Date")]
		public System.Nullable<System.DateTime> Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this._Thursday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Date")]
		public System.Nullable<System.DateTime> Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this._Friday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayTask", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MondayTask
		{
			get
			{
				return this._MondayTask;
			}
			set
			{
				if ((this._MondayTask != value))
				{
					this._MondayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayTask", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TuesdayTask
		{
			get
			{
				return this._TuesdayTask;
			}
			set
			{
				if ((this._TuesdayTask != value))
				{
					this._TuesdayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayTask", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string WednesdayTask
		{
			get
			{
				return this._WednesdayTask;
			}
			set
			{
				if ((this._WednesdayTask != value))
				{
					this._WednesdayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayTask", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ThursdayTask
		{
			get
			{
				return this._ThursdayTask;
			}
			set
			{
				if ((this._ThursdayTask != value))
				{
					this._ThursdayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayTask", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FridayTask
		{
			get
			{
				return this._FridayTask;
			}
			set
			{
				if ((this._FridayTask != value))
				{
					this._FridayTask = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MondayHours", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MondayHours
		{
			get
			{
				return this._MondayHours;
			}
			set
			{
				if ((this._MondayHours != value))
				{
					this._MondayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuesdayHours", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TuesdayHours
		{
			get
			{
				return this._TuesdayHours;
			}
			set
			{
				if ((this._TuesdayHours != value))
				{
					this._TuesdayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WednesdayHours", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string WednesdayHours
		{
			get
			{
				return this._WednesdayHours;
			}
			set
			{
				if ((this._WednesdayHours != value))
				{
					this._WednesdayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThursdayHours", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ThursdayHours
		{
			get
			{
				return this._ThursdayHours;
			}
			set
			{
				if ((this._ThursdayHours != value))
				{
					this._ThursdayHours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FridayHours", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string FridayHours
		{
			get
			{
				return this._FridayHours;
			}
			set
			{
				if ((this._FridayHours != value))
				{
					this._FridayHours = value;
				}
			}
		}
	}
	
	public partial class sp_loadAssigntask_tocalendarResult
	{
		
		private System.Nullable<System.DateTime> _WORKINGDATE;
		
		public sp_loadAssigntask_tocalendarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKINGDATE", DbType="Date")]
		public System.Nullable<System.DateTime> WORKINGDATE
		{
			get
			{
				return this._WORKINGDATE;
			}
			set
			{
				if ((this._WORKINGDATE != value))
				{
					this._WORKINGDATE = value;
				}
			}
		}
	}
	
	public partial class sp_loadEmpAssigntask_tocalendarResult
	{
		
		private System.Nullable<System.DateTime> _WORKINGDATE;
		
		public sp_loadEmpAssigntask_tocalendarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKINGDATE", DbType="Date")]
		public System.Nullable<System.DateTime> WORKINGDATE
		{
			get
			{
				return this._WORKINGDATE;
			}
			set
			{
				if ((this._WORKINGDATE != value))
				{
					this._WORKINGDATE = value;
				}
			}
		}
	}
	
	public partial class sp_Load_PlannedActivitiesResult
	{
		
		private string _PERNR;
		
		private string _ENAME;
		
		private string _EMP_DEPART;
		
		private System.Nullable<System.DateTime> _WORKINGDATE;
		
		private string _CATSHOURS;
		
		private string _WORKASSIGNED;
		
		public sp_Load_PlannedActivitiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENAME", DbType="VarChar(50)")]
		public string ENAME
		{
			get
			{
				return this._ENAME;
			}
			set
			{
				if ((this._ENAME != value))
				{
					this._ENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_DEPART", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EMP_DEPART
		{
			get
			{
				return this._EMP_DEPART;
			}
			set
			{
				if ((this._EMP_DEPART != value))
				{
					this._EMP_DEPART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKINGDATE", DbType="Date")]
		public System.Nullable<System.DateTime> WORKINGDATE
		{
			get
			{
				return this._WORKINGDATE;
			}
			set
			{
				if ((this._WORKINGDATE != value))
				{
					this._WORKINGDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATSHOURS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CATSHOURS
		{
			get
			{
				return this._CATSHOURS;
			}
			set
			{
				if ((this._CATSHOURS != value))
				{
					this._CATSHOURS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKASSIGNED", DbType="NVarChar(MAX)")]
		public string WORKASSIGNED
		{
			get
			{
				return this._WORKASSIGNED;
			}
			set
			{
				if ((this._WORKASSIGNED != value))
				{
					this._WORKASSIGNED = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_recordworking_time_dateResult
	{
		
		private System.Nullable<System.DateTime> _Fromdate;
		
		public sp_wt_get_recordworking_time_dateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fromdate", DbType="Date")]
		public System.Nullable<System.DateTime> Fromdate
		{
			get
			{
				return this._Fromdate;
			}
			set
			{
				if ((this._Fromdate != value))
				{
					this._Fromdate = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_recordworking_timeResult
	{
		
		private string _CURRECORDNO;
		
		private string _AWART;
		
		private string _CATSHOURS;
		
		private System.Nullable<System.DateTime> _WORKINGDATE;
		
		private string _day;
		
		private string _cost_center;
		
		private string _order_type;
		
		private string _RPROJ;
		
		private string _RNPLNR;
		
		private string _VORNR;
		
		private string _status;
		
		private long _TID;
		
		private string _Plndhrs;
		
		public sp_wt_get_recordworking_timeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRECORDNO", DbType="VarChar(50)")]
		public string CURRECORDNO
		{
			get
			{
				return this._CURRECORDNO;
			}
			set
			{
				if ((this._CURRECORDNO != value))
				{
					this._CURRECORDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATSHOURS", DbType="VarChar(50)")]
		public string CATSHOURS
		{
			get
			{
				return this._CATSHOURS;
			}
			set
			{
				if ((this._CATSHOURS != value))
				{
					this._CATSHOURS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKINGDATE", DbType="Date")]
		public System.Nullable<System.DateTime> WORKINGDATE
		{
			get
			{
				return this._WORKINGDATE;
			}
			set
			{
				if ((this._WORKINGDATE != value))
				{
					this._WORKINGDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day", DbType="NVarChar(30)")]
		public string day
		{
			get
			{
				return this._day;
			}
			set
			{
				if ((this._day != value))
				{
					this._day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_center", DbType="VarChar(50)")]
		public string cost_center
		{
			get
			{
				return this._cost_center;
			}
			set
			{
				if ((this._cost_center != value))
				{
					this._cost_center = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_type", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string order_type
		{
			get
			{
				return this._order_type;
			}
			set
			{
				if ((this._order_type != value))
				{
					this._order_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPROJ", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RPROJ
		{
			get
			{
				return this._RPROJ;
			}
			set
			{
				if ((this._RPROJ != value))
				{
					this._RPROJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNPLNR", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RNPLNR
		{
			get
			{
				return this._RNPLNR;
			}
			set
			{
				if ((this._RNPLNR != value))
				{
					this._RNPLNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VORNR", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string VORNR
		{
			get
			{
				return this._VORNR;
			}
			set
			{
				if ((this._VORNR != value))
				{
					this._VORNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TID", DbType="BigInt NOT NULL")]
		public long TID
		{
			get
			{
				return this._TID;
			}
			set
			{
				if ((this._TID != value))
				{
					this._TID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plndhrs", DbType="VarChar(MAX)")]
		public string Plndhrs
		{
			get
			{
				return this._Plndhrs;
			}
			set
			{
				if ((this._Plndhrs != value))
				{
					this._Plndhrs = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_recordworking_time_weekResult
	{
		
		private string _CURRECORDNO;
		
		private string _AWART;
		
		private string _cost_center;
		
		private string _order_type;
		
		private string _Monday;
		
		private string _Tuesday;
		
		private string _Wednesday;
		
		private string _Thursday;
		
		private string _Friday;
		
		private string _Saturday;
		
		private string _Sunday;
		
		private string _RPROJ;
		
		private string _RNPLNR;
		
		private string _VORNR;
		
		private string _REMARKS;
		
		private long _TID;
		
		private string _Plndhrs;
		
		public sp_wt_get_recordworking_time_weekResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRECORDNO", DbType="VarChar(50)")]
		public string CURRECORDNO
		{
			get
			{
				return this._CURRECORDNO;
			}
			set
			{
				if ((this._CURRECORDNO != value))
				{
					this._CURRECORDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWART", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AWART
		{
			get
			{
				return this._AWART;
			}
			set
			{
				if ((this._AWART != value))
				{
					this._AWART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_center", DbType="VarChar(50)")]
		public string cost_center
		{
			get
			{
				return this._cost_center;
			}
			set
			{
				if ((this._cost_center != value))
				{
					this._cost_center = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_type", DbType="VarChar(50)")]
		public string order_type
		{
			get
			{
				return this._order_type;
			}
			set
			{
				if ((this._order_type != value))
				{
					this._order_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="VarChar(20)")]
		public string Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this._Monday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuesday", DbType="VarChar(20)")]
		public string Tuesday
		{
			get
			{
				return this._Tuesday;
			}
			set
			{
				if ((this._Tuesday != value))
				{
					this._Tuesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wednesday", DbType="VarChar(20)")]
		public string Wednesday
		{
			get
			{
				return this._Wednesday;
			}
			set
			{
				if ((this._Wednesday != value))
				{
					this._Wednesday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thursday", DbType="VarChar(20)")]
		public string Thursday
		{
			get
			{
				return this._Thursday;
			}
			set
			{
				if ((this._Thursday != value))
				{
					this._Thursday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="VarChar(20)")]
		public string Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this._Friday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="VarChar(20)")]
		public string Saturday
		{
			get
			{
				return this._Saturday;
			}
			set
			{
				if ((this._Saturday != value))
				{
					this._Saturday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="VarChar(20)")]
		public string Sunday
		{
			get
			{
				return this._Sunday;
			}
			set
			{
				if ((this._Sunday != value))
				{
					this._Sunday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPROJ", DbType="VarChar(100)")]
		public string RPROJ
		{
			get
			{
				return this._RPROJ;
			}
			set
			{
				if ((this._RPROJ != value))
				{
					this._RPROJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNPLNR", DbType="VarChar(100)")]
		public string RNPLNR
		{
			get
			{
				return this._RNPLNR;
			}
			set
			{
				if ((this._RNPLNR != value))
				{
					this._RNPLNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VORNR", DbType="VarChar(100)")]
		public string VORNR
		{
			get
			{
				return this._VORNR;
			}
			set
			{
				if ((this._VORNR != value))
				{
					this._VORNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TID", DbType="BigInt NOT NULL")]
		public long TID
		{
			get
			{
				return this._TID;
			}
			set
			{
				if ((this._TID != value))
				{
					this._TID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plndhrs", DbType="VarChar(MAX)")]
		public string Plndhrs
		{
			get
			{
				return this._Plndhrs;
			}
			set
			{
				if ((this._Plndhrs != value))
				{
					this._Plndhrs = value;
				}
			}
		}
	}
	
	public partial class sp_wt_get_recordworking_time_MailResult
	{
		
		private System.Nullable<System.DateTime> _MinDate;
		
		private System.Nullable<System.DateTime> _MaxDate;
		
		public sp_wt_get_recordworking_time_MailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDate", DbType="Date")]
		public System.Nullable<System.DateTime> MinDate
		{
			get
			{
				return this._MinDate;
			}
			set
			{
				if ((this._MinDate != value))
				{
					this._MinDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDate", DbType="Date")]
		public System.Nullable<System.DateTime> MaxDate
		{
			get
			{
				return this._MaxDate;
			}
			set
			{
				if ((this._MaxDate != value))
				{
					this._MaxDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
