<?xml version="1.0" encoding="utf-8"?><Database Name="PrismRangson120420217" Class="personaldatadalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS2012;Initial Catalog=PrismRangson120420217;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iEmpPowerConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_conf_checkvalidation_for_personal_data_information" Method="sp_conf_checkvalidation_for_personal_data_information">
    <ElementType Name="sp_conf_checkvalidation_for_personal_data_informationResult">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[values]" Member="values" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_load_personal_hr_data" Method="sp_pi_load_personal_hr_data">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_pi_load_personal_hr_dataResult">
      <Column Name="PHOTO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SPRSL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="GESCH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="GBDAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GBORT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="GBLND" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="NATI0" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="GBDEP" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="NATI2" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="NATI3" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="FAMST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FAMDT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ANZKD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KONFE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="isupdate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_update_personal_data" Method="sp_pi_update_personal_data">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TITEL" Parameter="tITEL" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="VORNA" Parameter="vORNA" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="NACHN" Parameter="nACHN" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="NAME2" Parameter="nAME2" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="INITS" Parameter="iNITS" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="RUFNM" Parameter="rUFNM" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="SPRSL" Parameter="sPRSL" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="GESCH" Parameter="gESCH" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="GBDAT" Parameter="gBDAT" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="GBORT" Parameter="gBORT" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="GBLND" Parameter="gBLND" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NATI0" Parameter="nATI0" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="GBDEP" Parameter="gBDEP" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NATI2" Parameter="nATI2" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NATI3" Parameter="nATI3" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="FAMST" Parameter="fAMST" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="FAMDT" Parameter="fAMDT" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ANZKD" Parameter="aNZKD" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="KITXT" Parameter="kITXT" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PHOTO" Parameter="pHOTO" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SuperVisorStatus" Parameter="superVisorStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HRStatus" Parameter="hRStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HR_Name" Parameter="hR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Name" Parameter="superVisor_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Email" Parameter="superVisor_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="Pernr_Email" Parameter="pernr_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Phn" Parameter="hR_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="SuperVisor_Phn" Parameter="superVisor_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_pi_personal_details" Method="usp_pi_personal_details">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PHOTO" Parameter="pHOTO" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TITEL" Parameter="tITEL" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="VORNA" Parameter="vORNA" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="NACHN" Parameter="nACHN" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="NAME2" Parameter="nAME2" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="INITS" Parameter="iNITS" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="RUFNM" Parameter="rUFNM" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="SPRSL" Parameter="sPRSL" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="GESCH" Parameter="gESCH" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="GBDAT" Parameter="gBDAT" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="GBORT" Parameter="gBORT" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="GBLND" Parameter="gBLND" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NATI0" Parameter="nATI0" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="GBDEP" Parameter="gBDEP" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NATI2" Parameter="nATI2" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NATI3" Parameter="nATI3" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="FAMST" Parameter="fAMST" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="FAMDT" Parameter="fAMDT" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ANZKD" Parameter="aNZKD" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="KONFE" Parameter="kONFE" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="BEGDA" Parameter="bEGDA" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ENDDA" Parameter="eNDDA" Type="System.DateTime" DbType="Date" />
    <Parameter Name="created_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="created_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="STATUS" Parameter="sTATUS" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Flag" Parameter="flag" Type="System.Int32" DbType="Int" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="Supervisor_Email" Parameter="supervisor_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="PERNR_Name" Parameter="pERNR_Name" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="PERNR_Email" Parameter="pERNR_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_pi_load_personal_name_data" Method="sp_pi_load_personal_name_data">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_pi_load_personal_name_dataResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PERNR" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TITEL" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PHOTO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATEXT" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="VORNA" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="NACHN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="NAME2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="INITS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RUFNM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SPRSL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SPTXT" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="GESCH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GBORT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="KONFE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="KTEXT" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="GBLND" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="LANDX" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="GBDEP" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="BLAND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="NATI0" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="NATIO" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="NATI2" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="LANDX2" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="NATI3" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="LANDX3" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="FAMST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FTEXT" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="FAMDT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ANZKD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TransStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_get_PersonalDatainfo_mail" Method="sp_pi_get_PersonalDatainfo_mail">
    <Parameter Name="pkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="sts" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_pi_get_PersonalDatainfo_mailResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ATEXT" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="VORNA" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="NACHN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="NAME2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="INITS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="GBDAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LANDX" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="BEZEI" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="GBORT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SPTXT" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="KTEXT" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="NATIO" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="LANDX2" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="LANDX3" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="FTEXT" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="FAMDT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ANZKD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>