<?xml version="1.0" encoding="utf-8"?><Database Name="Paycompute_NewUIPRD" Class="piaddressinformationdalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS2012;Initial Catalog=Paycompute_NewUIPRD;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PayCompute20032020ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_conf_checkvalidation_for_address_information" Method="sp_conf_checkvalidation_for_address_information">
    <ElementType Name="sp_conf_checkvalidation_for_address_informationResult">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[values]" Member="values" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_update_address_details" Method="sp_pi_update_address_details">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="SUBTY" Parameter="sUBTY" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="BEGDA" Parameter="bEGDA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ENDDA" Parameter="eNDDA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="STRAS" Parameter="sTRAS" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="LOCAT" Parameter="lOCAT" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="FGBLD" Parameter="fGBLD" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="STATE" Parameter="sTATE" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="ORT01" Parameter="oRT01" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="PSTLZ" Parameter="pSTLZ" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TELNR" Parameter="tELNR" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="Old_SUBTY" Parameter="old_SUBTY" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="old_BEGDA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="old_ENDDA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="isapproved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="isactive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="approved_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="approved_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SuperVisorStatus" Parameter="superVisorStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HRStatus" Parameter="hRStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HR_Name" Parameter="hR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Name" Parameter="superVisor_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Email" Parameter="superVisor_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="PERNR_Name" Parameter="pERNR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="PERNR_Email" Parameter="pERNR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Phn" Parameter="hR_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="SuperVisor_Phn" Parameter="superVisor_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_pi_create_address_details" Method="sp_pi_create_address_details">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="SUBTY" Parameter="sUBTY" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="BEGDA" Parameter="bEGDA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ENDDA" Parameter="eNDDA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="STRAS" Parameter="sTRAS" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="LOCAT" Parameter="lOCAT" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="FGBLD" Parameter="fGBLD" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="STATE" Parameter="sTATE" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="ORT01" Parameter="oRT01" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="PSTLZ" Parameter="pSTLZ" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TELNR" Parameter="tELNR" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="sTC" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="created_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="created_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="isapproved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="isactive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="approved_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="approved_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="hr_approved_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="hr_approved_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="hr_approved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="hr_status" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="SuperVisorStatus" Parameter="superVisorStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HRStatus" Parameter="hRStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HR_Name" Parameter="hR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Phn" Parameter="hR_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="SuperVisor_Name" Parameter="superVisor_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Phn" Parameter="superVisor_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Email" Parameter="superVisor_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="PERNR_Name" Parameter="pERNR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="PERNR_Email" Parameter="pERNR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_pi_get_address_info" Method="sp_pi_get_address_info">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_pi_get_address_infoResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BEGDA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ENDDA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STRAS" Type="System.String" DbType="VarChar(113)" CanBeNull="true" />
      <Column Name="RecordCnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_get_address_info_full" Method="sp_pi_get_address_info_full">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_pi_get_address_info_fullResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pkey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PERNR" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SUBTY" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BEGDA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ENDDA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STRAS" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="LOCAT" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="FGBLD" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="LANDX" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BEZEI" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="ORT01" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="PSTLZ" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TELNR" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TransStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_get_Addressinfo_mail" Method="sp_pi_get_Addressinfo_mail">
    <Parameter Name="pkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="sts" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_pi_get_Addressinfo_mailResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PKEY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Address Type]" Member="Address_Type" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="[Valid from]" Member="Valid_from" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[Valid to]" Member="Valid_to" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[House number &amp; street]" Member="House_number___street" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="[Address line 2]" Member="Address_line_2" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Country Name]" Member="Country_Name" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="[State Name]" Member="State_Name" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Postal Code]" Member="Postal_Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="[Telephone Number]" Member="Telephone_Number" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_pi_address_details" Method="usp_pi_address_details">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SUBTY" Parameter="sUBTY" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="BEGDA" Parameter="bEGDA" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ENDDA" Parameter="eNDDA" Type="System.DateTime" DbType="Date" />
    <Parameter Name="STRAS" Parameter="sTRAS" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="LOCAT" Parameter="lOCAT" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="FGBLD" Parameter="fGBLD" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="STATE" Parameter="sTATE" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="ORT01" Parameter="oRT01" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="PSTLZ" Parameter="pSTLZ" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TELNR" Parameter="tELNR" Type="System.String" DbType="VarChar(14)" />
    <Parameter Name="created_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="created_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="STATUS" Parameter="sTATUS" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Flag" Parameter="flag" Type="System.Int32" DbType="Int" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="Supervisor_Email" Parameter="supervisor_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="PERNR_Name" Parameter="pERNR_Name" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="PERNR_Email" Parameter="pERNR_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>