#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iEmpPower.Old_App_Code.iEmpPowerDAL.Personal_Information
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paycompute_NewUIPRD")]
	public partial class pibankinformationdalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public pibankinformationdalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iEmpPowerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pibankinformationdalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pibankinformationdalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pibankinformationdalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pibankinformationdalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_conf_checkvalidation_for_bank_info")]
		public ISingleResult<sp_conf_checkvalidation_for_bank_infoResult> sp_conf_checkvalidation_for_bank_info()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_conf_checkvalidation_for_bank_infoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_create_bank_info")]
		public int sp_pi_create_bank_info(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBTY", DbType="VarChar(4)")] string sUBTY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMFTX", DbType="VarChar(40)")] string eMFTX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BKPLZ", DbType="VarChar(10)")] string bKPLZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BKORT", DbType="VarChar(40)")] string bKORT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BANKS", DbType="VarChar(3)")] string bANKS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BANKL", DbType="VarChar(15)")] string bANKL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BANKN", DbType="VarChar(18)")] string bANKN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZLSCH", DbType="Char(1)")] System.Nullable<char> zLSCH, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZWECK", DbType="VarChar(40)")] string zWECK, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WAERS", DbType="VarChar(5)")] string wAERS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_on, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string created_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isapproved, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isactive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> modified_on, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modified_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HRStatus", DbType="Bit")] ref System.Nullable<bool> hRStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Pernr", DbType="VarChar(100)")] ref string hR_Pernr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Pernr", DbType="VarChar(100)")] ref string superVisor_Pernr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(100)")] ref string hR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] ref string pernrEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Phn", DbType="VarChar(15)")] ref string hR_Phn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Phn", DbType="VarChar(15)")] ref string superVisor_Phn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, sUBTY, eMFTX, bKPLZ, bKORT, bANKS, bANKL, bANKN, zLSCH, zWECK, wAERS, created_on, created_by, isapproved, isactive, modified_on, modified_by, superVisorStatus, hRStatus, hR_Pernr, superVisor_Pernr, hR_Email, superVisor_Email, pernrEmail, hR_Phn, superVisor_Phn);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(17)));
			hRStatus = ((System.Nullable<bool>)(result.GetParameterValue(18)));
			hR_Pernr = ((string)(result.GetParameterValue(19)));
			superVisor_Pernr = ((string)(result.GetParameterValue(20)));
			hR_Email = ((string)(result.GetParameterValue(21)));
			superVisor_Email = ((string)(result.GetParameterValue(22)));
			pernrEmail = ((string)(result.GetParameterValue(23)));
			hR_Phn = ((string)(result.GetParameterValue(24)));
			superVisor_Phn = ((string)(result.GetParameterValue(25)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_update_bank_info")]
		public int sp_pi_update_bank_info(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBTY", DbType="VarChar(4)")] string sUBTY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMFTX", DbType="VarChar(40)")] string eMFTX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BKPLZ", DbType="VarChar(10)")] string bKPLZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BKORT", DbType="VarChar(40)")] string bKORT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BANKS", DbType="VarChar(3)")] string bANKS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BANKL", DbType="VarChar(15)")] string bANKL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BANKN", DbType="VarChar(18)")] string bANKN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZLSCH", DbType="Char(1)")] System.Nullable<char> zLSCH, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZWECK", DbType="VarChar(40)")] string zWECK, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WAERS", DbType="VarChar(5)")] string wAERS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OLD_BANKN", DbType="VarChar(18)")] string oLD_BANKN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> modified_on, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modified_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string pkey, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HRStatus", DbType="Bit")] ref System.Nullable<bool> hRStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Pernr", DbType="VarChar(100)")] ref string hR_Pernr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Pernr", DbType="VarChar(100)")] ref string superVisor_Pernr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(100)")] ref string hR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] ref string pernrEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Phn", DbType="VarChar(15)")] ref string hR_Phn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Phn", DbType="VarChar(15)")] ref string superVisor_Phn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, sUBTY, eMFTX, bKPLZ, bKORT, bANKS, bANKL, bANKN, zLSCH, zWECK, wAERS, oLD_BANKN, modified_on, modified_by, pkey, superVisorStatus, hRStatus, hR_Pernr, superVisor_Pernr, hR_Email, superVisor_Email, pernrEmail, hR_Phn, superVisor_Phn);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(15)));
			hRStatus = ((System.Nullable<bool>)(result.GetParameterValue(16)));
			hR_Pernr = ((string)(result.GetParameterValue(17)));
			superVisor_Pernr = ((string)(result.GetParameterValue(18)));
			hR_Email = ((string)(result.GetParameterValue(19)));
			superVisor_Email = ((string)(result.GetParameterValue(20)));
			pernrEmail = ((string)(result.GetParameterValue(21)));
			hR_Phn = ((string)(result.GetParameterValue(22)));
			superVisor_Phn = ((string)(result.GetParameterValue(23)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_bank_info_full")]
		public ISingleResult<sp_pi_get_bank_info_fullResult> sp_pi_get_bank_info_full([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(100)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, iD);
			return ((ISingleResult<sp_pi_get_bank_info_fullResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_bank_info")]
		public ISingleResult<sp_pi_get_bank_infoResult> sp_pi_get_bank_info([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, pageIndex, pageSize);
			return ((ISingleResult<sp_pi_get_bank_infoResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_conf_checkvalidation_for_bank_infoResult
	{
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<bool> _values;
		
		public sp_conf_checkvalidation_for_bank_infoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[values]", Storage="_values", DbType="Bit")]
		public System.Nullable<bool> values
		{
			get
			{
				return this._values;
			}
			set
			{
				if ((this._values != value))
				{
					this._values = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_bank_info_fullResult
	{
		
		private System.Guid _ID;
		
		private string _PERNR;
		
		private string _SUBTY;
		
		private string _EMFTX;
		
		private string _BKPLZ;
		
		private string _BKORT;
		
		private string _BANKS;
		
		private string _BANKL;
		
		private string _BANKN;
		
		private System.Nullable<char> _ZLSCH;
		
		private string _ZWECK;
		
		private string _WAERS;
		
		private string _LANDX;
		
		private string _TEXT1;
		
		private string _LTEXT;
		
		private string _STEXT;
		
		public sp_pi_get_bank_info_fullResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTY", DbType="VarChar(4)")]
		public string SUBTY
		{
			get
			{
				return this._SUBTY;
			}
			set
			{
				if ((this._SUBTY != value))
				{
					this._SUBTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMFTX", DbType="VarChar(40)")]
		public string EMFTX
		{
			get
			{
				return this._EMFTX;
			}
			set
			{
				if ((this._EMFTX != value))
				{
					this._EMFTX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BKPLZ", DbType="VarChar(10)")]
		public string BKPLZ
		{
			get
			{
				return this._BKPLZ;
			}
			set
			{
				if ((this._BKPLZ != value))
				{
					this._BKPLZ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BKORT", DbType="VarChar(40)")]
		public string BKORT
		{
			get
			{
				return this._BKORT;
			}
			set
			{
				if ((this._BKORT != value))
				{
					this._BKORT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKS", DbType="VarChar(3)")]
		public string BANKS
		{
			get
			{
				return this._BANKS;
			}
			set
			{
				if ((this._BANKS != value))
				{
					this._BANKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKL", DbType="VarChar(15)")]
		public string BANKL
		{
			get
			{
				return this._BANKL;
			}
			set
			{
				if ((this._BANKL != value))
				{
					this._BANKL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKN", DbType="VarChar(18)")]
		public string BANKN
		{
			get
			{
				return this._BANKN;
			}
			set
			{
				if ((this._BANKN != value))
				{
					this._BANKN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZLSCH", DbType="Char(1)")]
		public System.Nullable<char> ZLSCH
		{
			get
			{
				return this._ZLSCH;
			}
			set
			{
				if ((this._ZLSCH != value))
				{
					this._ZLSCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZWECK", DbType="VarChar(40)")]
		public string ZWECK
		{
			get
			{
				return this._ZWECK;
			}
			set
			{
				if ((this._ZWECK != value))
				{
					this._ZWECK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAERS", DbType="VarChar(5)")]
		public string WAERS
		{
			get
			{
				return this._WAERS;
			}
			set
			{
				if ((this._WAERS != value))
				{
					this._WAERS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDX", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string LANDX
		{
			get
			{
				return this._LANDX;
			}
			set
			{
				if ((this._LANDX != value))
				{
					this._LANDX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEXT1", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string TEXT1
		{
			get
			{
				return this._TEXT1;
			}
			set
			{
				if ((this._TEXT1 != value))
				{
					this._TEXT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTEXT", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string LTEXT
		{
			get
			{
				return this._LTEXT;
			}
			set
			{
				if ((this._LTEXT != value))
				{
					this._LTEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEXT", DbType="VarChar(40)")]
		public string STEXT
		{
			get
			{
				return this._STEXT;
			}
			set
			{
				if ((this._STEXT != value))
				{
					this._STEXT = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_bank_infoResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private System.Guid _ID;
		
		private string _pkey;
		
		private string _BANKS;
		
		private string _BANKL;
		
		private string _BANKN;
		
		private string _WAERS;
		
		private string _LANDX;
		
		private string _TEXT1;
		
		private string _LTEXT;
		
		private string _STEXT;
		
		private System.Nullable<int> _RecordCnt;
		
		public sp_pi_get_bank_infoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkey", DbType="VarChar(50)")]
		public string pkey
		{
			get
			{
				return this._pkey;
			}
			set
			{
				if ((this._pkey != value))
				{
					this._pkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKS", DbType="VarChar(3)")]
		public string BANKS
		{
			get
			{
				return this._BANKS;
			}
			set
			{
				if ((this._BANKS != value))
				{
					this._BANKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKL", DbType="VarChar(15)")]
		public string BANKL
		{
			get
			{
				return this._BANKL;
			}
			set
			{
				if ((this._BANKL != value))
				{
					this._BANKL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKN", DbType="VarChar(18)")]
		public string BANKN
		{
			get
			{
				return this._BANKN;
			}
			set
			{
				if ((this._BANKN != value))
				{
					this._BANKN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAERS", DbType="VarChar(5)")]
		public string WAERS
		{
			get
			{
				return this._WAERS;
			}
			set
			{
				if ((this._WAERS != value))
				{
					this._WAERS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDX", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string LANDX
		{
			get
			{
				return this._LANDX;
			}
			set
			{
				if ((this._LANDX != value))
				{
					this._LANDX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEXT1", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string TEXT1
		{
			get
			{
				return this._TEXT1;
			}
			set
			{
				if ((this._TEXT1 != value))
				{
					this._TEXT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTEXT", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string LTEXT
		{
			get
			{
				return this._LTEXT;
			}
			set
			{
				if ((this._LTEXT != value))
				{
					this._LTEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEXT", DbType="VarChar(40)")]
		public string STEXT
		{
			get
			{
				return this._STEXT;
			}
			set
			{
				if ((this._STEXT != value))
				{
					this._STEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCnt", DbType="Int")]
		public System.Nullable<int> RecordCnt
		{
			get
			{
				return this._RecordCnt;
			}
			set
			{
				if ((this._RecordCnt != value))
				{
					this._RecordCnt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
