<?xml version="1.0" encoding="utf-8"?><Database Name="PrismRangson120420217" Class="pifamilymembersdalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS2012;Initial Catalog=PrismRangson120420217;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iEmpPowerConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_conf_checkvalidation_for_family_member_information" Method="sp_conf_checkvalidation_for_family_member_information">
    <ElementType Name="sp_conf_checkvalidation_for_family_member_informationResult">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[values]" Member="values" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_check_family_members" Method="sp_pi_check_family_members">
    <Parameter Name="employee_id" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_pi_check_family_membersResult">
      <Column Name="FAMSA" Type="System.String" DbType="Char(4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_create_family_members" Method="sp_pi_create_family_members">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FAMSA" Parameter="fAMSA" Type="System.String" DbType="Char(4)" />
    <Parameter Name="FAVOR" Parameter="fAVOR" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FANAM" Parameter="fANAM" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FGBNA" Parameter="fGBNA" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FINIT" Parameter="fINIT" Type="System.String" DbType="Char(10)" />
    <Parameter Name="FNMZU" Parameter="fNMZU" Type="System.String" DbType="Char(15)" />
    <Parameter Name="FVRSW" Parameter="fVRSW" Type="System.String" DbType="Char(15)" />
    <Parameter Name="FASEX" Parameter="fASEX" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="FGBDT" Parameter="fGBDT" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FGBOT" Parameter="fGBOT" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FGBLD" Parameter="fGBLD" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANAT" Parameter="fANAT" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANA2" Parameter="fANA2" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANA3" Parameter="fANA3" Type="System.String" DbType="Char(3)" />
    <Parameter Name="KDBSL" Parameter="kDBSL" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="KDBGR" Parameter="kDBGR" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="KDZUL" Parameter="kDZUL" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="created_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="created_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SuperVisorStatus" Parameter="superVisorStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HRStatus" Parameter="hRStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HR_Name" Parameter="hR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Name" Parameter="superVisor_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Email" Parameter="superVisor_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="pernrEmail" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Phn" Parameter="hR_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="SuperVisor_Phn" Parameter="superVisor_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_pi_update_family_members" Method="sp_pi_update_family_members">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FAMSA" Parameter="fAMSA" Type="System.String" DbType="Char(4)" />
    <Parameter Name="FAVOR" Parameter="fAVOR" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FANAM" Parameter="fANAM" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FGBNA" Parameter="fGBNA" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FINIT" Parameter="fINIT" Type="System.String" DbType="Char(10)" />
    <Parameter Name="FNMZU" Parameter="fNMZU" Type="System.String" DbType="Char(15)" />
    <Parameter Name="FVRSW" Parameter="fVRSW" Type="System.String" DbType="Char(15)" />
    <Parameter Name="FASEX" Parameter="fASEX" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="FGBDT" Parameter="fGBDT" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FGBOT" Parameter="fGBOT" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FGBLD" Parameter="fGBLD" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANAT" Parameter="fANAT" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANA2" Parameter="fANA2" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANA3" Parameter="fANA3" Type="System.String" DbType="Char(3)" />
    <Parameter Name="KDBSL" Parameter="kDBSL" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="KDBGR" Parameter="kDBGR" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="KDZUL" Parameter="kDZUL" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="OLD_FAVOR" Parameter="oLD_FAVOR" Type="System.String" DbType="Char(40)" />
    <Parameter Name="OLD_FAMSA" Parameter="oLD_FAMSA" Type="System.String" DbType="Char(4)" />
    <Parameter Name="OLD_FANAM" Parameter="oLD_FANAM" Type="System.String" DbType="Char(40)" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="pkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="OBJPS" Parameter="oBJPS" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="SuperVisorStatus" Parameter="superVisorStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HRStatus" Parameter="hRStatus" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HR_Name" Parameter="hR_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Name" Parameter="superVisor_Name" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="SuperVisor_Email" Parameter="superVisor_Email" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="pernrEmail" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Parameter Name="HR_Phn" Parameter="hR_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Parameter Name="SuperVisor_Phn" Parameter="superVisor_Phn" Type="System.String" DbType="VarChar(15)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_pi_get_family_members_type" Method="sp_pi_get_family_members_type">
    <ElementType Name="sp_pi_get_family_members_typeResult">
      <Column Name="SUBTY" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_get_family_members" Method="sp_pi_get_family_members">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_pi_get_family_membersResult">
      <Column Name="RowNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FAMSA" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="FAVOR" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FANAM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FGBDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Age" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="RecordCnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_pi_get_family_members_full" Method="sp_pi_get_family_members_full">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_pi_get_family_members_fullResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FAMSA" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FASEX" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="FAVOR" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FANAM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FGBDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KDBSL" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="KDGBR" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="KDZUL" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TransStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_pi_family_details" Method="usp_pi_family_details">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FAMSA" Parameter="fAMSA" Type="System.String" DbType="Char(4)" />
    <Parameter Name="OBJPS" Parameter="oBJPS" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="FAVOR" Parameter="fAVOR" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="FANAM" Parameter="fANAM" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="FGBNA" Parameter="fGBNA" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="FINIT" Parameter="fINIT" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="FNMZU" Parameter="fNMZU" Type="System.String" DbType="Char(15)" />
    <Parameter Name="FVRSW" Parameter="fVRSW" Type="System.String" DbType="Char(15)" />
    <Parameter Name="FASEX" Parameter="fASEX" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="FGBDT" Parameter="fGBDT" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FGBOT" Parameter="fGBOT" Type="System.String" DbType="Char(40)" />
    <Parameter Name="FGBLD" Parameter="fGBLD" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANAT" Parameter="fANAT" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANA2" Parameter="fANA2" Type="System.String" DbType="Char(3)" />
    <Parameter Name="FANA3" Parameter="fANA3" Type="System.String" DbType="Char(3)" />
    <Parameter Name="KDBSL" Parameter="kDBSL" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="KDGBR" Parameter="kDGBR" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="KDZUL" Parameter="kDZUL" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="BEGDA" Parameter="bEGDA" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ENDDA" Parameter="eNDDA" Type="System.DateTime" DbType="Date" />
    <Parameter Name="created_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="created_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="modified_by" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="modified_on" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="STATUS" Parameter="sTATUS" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Flag" Parameter="flag" Type="System.Int32" DbType="Int" />
    <Parameter Name="HR_Email" Parameter="hR_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="Supervisor_Email" Parameter="supervisor_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="PERNR_Name" Parameter="pERNR_Name" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Parameter Name="PERNR_Email" Parameter="pERNR_Email" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_pi_get_Familyinfo_mail" Method="sp_pi_get_Familyinfo_mail">
    <Parameter Name="pkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="sts" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_pi_get_Familyinfo_mailResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FAVOR" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="FANAM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FGBDT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="KDBSL" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="KDGBR" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="KDZUL" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>