#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iEmpPower.Old_App_Code.iEmpPowerDAL.Personal_Information
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paycompute_NewUIPRD")]
	public partial class pipersonalidsdalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public pipersonalidsdalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iEmpPowerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pipersonalidsdalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pipersonalidsdalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pipersonalidsdalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pipersonalidsdalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_conf_checkvalidation_for_personal_ids")]
		public ISingleResult<sp_conf_checkvalidation_for_personal_idsResult> sp_conf_checkvalidation_for_personal_ids()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_conf_checkvalidation_for_personal_idsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_update_personal_ids")]
		public int sp_pi_update_personal_ids(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(8)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ICTYPE", DbType="Char(2)")] string iCTYPE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ICNUM", DbType="Char(30)")] string iCNUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OLD_ICNUM", DbType="Char(30)")] string oLD_ICNUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OLD_ICTYPE", DbType="Char(2)")] string oLD_ICTYPE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modified_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> modified_on, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HRStatus", DbType="Bit")] ref System.Nullable<bool> hRStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Name", DbType="VarChar(100)")] ref string hR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Name", DbType="VarChar(100)")] ref string superVisor_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(100)")] ref string hR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pernr_Email", DbType="VarChar(100)")] ref string pernr_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Phn", DbType="VarChar(15)")] ref string hR_Phn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Phn", DbType="VarChar(15)")] ref string superVisor_Phn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, iCTYPE, iCNUM, oLD_ICNUM, oLD_ICTYPE, modified_by, modified_on, superVisorStatus, hRStatus, hR_Name, superVisor_Name, hR_Email, superVisor_Email, pernr_Email, hR_Phn, superVisor_Phn);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			hRStatus = ((System.Nullable<bool>)(result.GetParameterValue(8)));
			hR_Name = ((string)(result.GetParameterValue(9)));
			superVisor_Name = ((string)(result.GetParameterValue(10)));
			hR_Email = ((string)(result.GetParameterValue(11)));
			superVisor_Email = ((string)(result.GetParameterValue(12)));
			pernr_Email = ((string)(result.GetParameterValue(13)));
			hR_Phn = ((string)(result.GetParameterValue(14)));
			superVisor_Phn = ((string)(result.GetParameterValue(15)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_create_personal_ids")]
		public int sp_pi_create_personal_ids([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ICTYPE", DbType="Char(2)")] string iCTYPE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ICNUM", DbType="Char(30)")] string iCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string created_by, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> created_on, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisorStatus", DbType="Bit")] ref System.Nullable<bool> superVisorStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HRStatus", DbType="Bit")] ref System.Nullable<bool> hRStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Name", DbType="VarChar(100)")] ref string hR_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Name", DbType="VarChar(100)")] ref string superVisor_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(100)")] ref string hR_Email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Email", DbType="VarChar(100)")] ref string superVisor_Email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Name", DbType="VarChar(100)")] ref string pERNR_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Email", DbType="VarChar(100)")] ref string pERNR_Email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Phn", DbType="VarChar(15)")] ref string hR_Phn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SuperVisor_Phn", DbType="VarChar(15)")] ref string superVisor_Phn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, iCTYPE, iCNUM, created_by, created_on, superVisorStatus, hRStatus, hR_Name, superVisor_Name, hR_Email, superVisor_Email, pERNR_Name, pERNR_Email, hR_Phn, superVisor_Phn);
			superVisorStatus = ((System.Nullable<bool>)(result.GetParameterValue(5)));
			hRStatus = ((System.Nullable<bool>)(result.GetParameterValue(6)));
			hR_Name = ((string)(result.GetParameterValue(7)));
			superVisor_Name = ((string)(result.GetParameterValue(8)));
			hR_Email = ((string)(result.GetParameterValue(9)));
			superVisor_Email = ((string)(result.GetParameterValue(10)));
			pERNR_Name = ((string)(result.GetParameterValue(11)));
			pERNR_Email = ((string)(result.GetParameterValue(12)));
			hR_Phn = ((string)(result.GetParameterValue(13)));
			superVisor_Phn = ((string)(result.GetParameterValue(14)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_Visa_Passport_Details")]
		public ISingleResult<sp_Get_Visa_Passport_DetailsResult> sp_Get_Visa_Passport_Details([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_Get_Visa_Passport_DetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_get_All_personal_ids")]
		public ISingleResult<sp_get_All_personal_idsResult> sp_get_All_personal_ids()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_get_All_personal_idsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[sp_get_master.ZTR_FLYER_NUMBER]")]
		public ISingleResult<sp_get_master_ZTR_FLYER_NUMBERResult> sp_get_master_ZTR_FLYER_NUMBER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(50)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_get_master_ZTR_FLYER_NUMBERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[sp_get_master.ZTR_TRAVEL_INS]")]
		public ISingleResult<sp_get_master_ZTR_TRAVEL_INSResult> sp_get_master_ZTR_TRAVEL_INS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(50)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_get_master_ZTR_TRAVEL_INSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[sp_get_master.ZTR_VISA]")]
		public ISingleResult<sp_get_master_ZTR_VISAResult> sp_get_master_ZTR_VISA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(50)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_get_master_ZTR_VISAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[sp_get_master.ZTR_PASSPORT]")]
		public ISingleResult<sp_get_master_ZTR_PASSPORTResult> sp_get_master_ZTR_PASSPORT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(50)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_get_master_ZTR_PASSPORTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_personal_ids_full")]
		public ISingleResult<sp_pi_get_personal_ids_fullResult> sp_pi_get_personal_ids_full([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, pERNR);
			return ((ISingleResult<sp_pi_get_personal_ids_fullResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_personal_ids")]
		public ISingleResult<sp_pi_get_personal_idsResult> sp_pi_get_personal_ids([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(10)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, pageIndex, pageSize);
			return ((ISingleResult<sp_pi_get_personal_idsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_pi_get_Personalidinfo_mail")]
		public ISingleResult<sp_pi_get_Personalidinfo_mailResult> sp_pi_get_Personalidinfo_mail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pkey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string sts)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pkey, iD, sts);
			return ((ISingleResult<sp_pi_get_Personalidinfo_mailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_get_PERNRPAN")]
		public ISingleResult<sp_get_PERNRPANResult> sp_get_PERNRPAN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(8)")] string pERNR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR);
			return ((ISingleResult<sp_get_PERNRPANResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.payc_Load_benefitsbased_onEmpid")]
		public ISingleResult<payc_Load_benefitsbased_onEmpidResult> payc_Load_benefitsbased_onEmpid([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpID", DbType="VarChar(20)")] string empID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empID, cc, flag);
			return ((ISingleResult<payc_Load_benefitsbased_onEmpidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_pi_personal_id_details")]
		public int usp_pi_personal_id_details(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(20)")] string pERNR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ICTYPE", DbType="VarChar(2)")] string iCTYPE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ICNUM", DbType="VarChar(30)")] string iCNUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMPDOC", DbType="VarChar(MAX)")] string eMPDOC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BEGDA", DbType="DateTime")] System.Nullable<System.DateTime> bEGDA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENDDA", DbType="DateTime")] System.Nullable<System.DateTime> eNDDA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string created_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> created_on, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modified_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> modified_on, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATUS", DbType="VarChar(20)")] string sTATUS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Int")] System.Nullable<int> flag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HR_Email", DbType="VarChar(200)")] ref string hR_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Supervisor_Email", DbType="VarChar(200)")] ref string supervisor_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Name", DbType="VarChar(200)")] ref string pERNR_Name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR_Email", DbType="VarChar(200)")] ref string pERNR_Email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, pERNR, iCTYPE, iCNUM, eMPDOC, bEGDA, eNDDA, created_by, created_on, modified_by, modified_on, sTATUS, flag, hR_Email, supervisor_Email, pERNR_Name, pERNR_Email);
			hR_Email = ((string)(result.GetParameterValue(13)));
			supervisor_Email = ((string)(result.GetParameterValue(14)));
			pERNR_Name = ((string)(result.GetParameterValue(15)));
			pERNR_Email = ((string)(result.GetParameterValue(16)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_set_car_details_pids")]
		public int usp_set_car_details_pids([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PERNR", DbType="VarChar(8)")] string pERNR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CC", DbType="Int")] System.Nullable<int> cC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Regdate", DbType="Date")] System.Nullable<System.DateTime> regdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string file, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RCNo", DbType="VarChar(50)")] string rCNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RCName", DbType="VarChar(150)")] string rCName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] ref System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CC1", DbType="Int")] ref System.Nullable<int> cC1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Regdate1", DbType="Date")] ref System.Nullable<System.DateTime> regdate1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] ref string file1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RCNo1", DbType="VarChar(50)")] ref string rCNo1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RCName1", DbType="VarChar(150)")] ref string rCName1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pERNR, cC, regdate, file, rCNo, rCName, flg, status, cC1, regdate1, file1, rCNo1, rCName1);
			status = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			cC1 = ((System.Nullable<int>)(result.GetParameterValue(8)));
			regdate1 = ((System.Nullable<System.DateTime>)(result.GetParameterValue(9)));
			file1 = ((string)(result.GetParameterValue(10)));
			rCNo1 = ((string)(result.GetParameterValue(11)));
			rCName1 = ((string)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_conf_checkvalidation_for_personal_idsResult
	{
		
		private string _name;
		
		private string _description;
		
		private bool _values;
		
		public sp_conf_checkvalidation_for_personal_idsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[values]", Storage="_values", DbType="Bit NOT NULL")]
		public bool values
		{
			get
			{
				return this._values;
			}
			set
			{
				if ((this._values != value))
				{
					this._values = value;
				}
			}
		}
	}
	
	public partial class sp_Get_Visa_Passport_DetailsResult
	{
		
		private string _PERNR;
		
		private string _ICTYPE;
		
		private string _ICNUM;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private string _ICTXT;
		
		public sp_Get_Visa_Passport_DetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTYPE", DbType="Char(2)")]
		public string ICTYPE
		{
			get
			{
				return this._ICTYPE;
			}
			set
			{
				if ((this._ICTYPE != value))
				{
					this._ICTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="Char(30)")]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this._ICNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTXT", DbType="Char(30)")]
		public string ICTXT
		{
			get
			{
				return this._ICTXT;
			}
			set
			{
				if ((this._ICTXT != value))
				{
					this._ICTXT = value;
				}
			}
		}
	}
	
	public partial class sp_get_All_personal_idsResult
	{
		
		private string _PERNR;
		
		private string _ICTYPE;
		
		private string _ICNUM;
		
		private string _status;
		
		private bool _isupdate;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private string _ICTXT;
		
		public sp_get_All_personal_idsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTYPE", DbType="Char(2)")]
		public string ICTYPE
		{
			get
			{
				return this._ICTYPE;
			}
			set
			{
				if ((this._ICTYPE != value))
				{
					this._ICTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="Char(30)")]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this._ICNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isupdate", DbType="Bit NOT NULL")]
		public bool isupdate
		{
			get
			{
				return this._isupdate;
			}
			set
			{
				if ((this._isupdate != value))
				{
					this._isupdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this._ENDDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTXT", DbType="Char(30)")]
		public string ICTXT
		{
			get
			{
				return this._ICTXT;
			}
			set
			{
				if ((this._ICTXT != value))
				{
					this._ICTXT = value;
				}
			}
		}
	}
	
	public partial class sp_get_master_ZTR_FLYER_NUMBERResult
	{
		
		private string _PERNR;
		
		private string _FRFLYNUM;
		
		private string _EMPNAME;
		
		private string _AIRLINE;
		
		private string _VALSTATUS;
		
		public sp_get_master_ZTR_FLYER_NUMBERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(8)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRFLYNUM", DbType="VarChar(50)")]
		public string FRFLYNUM
		{
			get
			{
				return this._FRFLYNUM;
			}
			set
			{
				if ((this._FRFLYNUM != value))
				{
					this._FRFLYNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNAME", DbType="VarChar(50)")]
		public string EMPNAME
		{
			get
			{
				return this._EMPNAME;
			}
			set
			{
				if ((this._EMPNAME != value))
				{
					this._EMPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AIRLINE", DbType="VarChar(50)")]
		public string AIRLINE
		{
			get
			{
				return this._AIRLINE;
			}
			set
			{
				if ((this._AIRLINE != value))
				{
					this._AIRLINE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALSTATUS", DbType="VarChar(50)")]
		public string VALSTATUS
		{
			get
			{
				return this._VALSTATUS;
			}
			set
			{
				if ((this._VALSTATUS != value))
				{
					this._VALSTATUS = value;
				}
			}
		}
	}
	
	public partial class sp_get_master_ZTR_TRAVEL_INSResult
	{
		
		private string _PERNR;
		
		private string _TRINSNO;
		
		private string _EMPNAME;
		
		private System.Nullable<System.DateTime> _DOI;
		
		private System.Nullable<System.DateTime> _DOE;
		
		private string _PLAN1;
		
		private string _PREMIUM;
		
		private string _AGENT_NAME;
		
		public sp_get_master_ZTR_TRAVEL_INSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(50)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINSNO", DbType="VarChar(50)")]
		public string TRINSNO
		{
			get
			{
				return this._TRINSNO;
			}
			set
			{
				if ((this._TRINSNO != value))
				{
					this._TRINSNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNAME", DbType="VarChar(50)")]
		public string EMPNAME
		{
			get
			{
				return this._EMPNAME;
			}
			set
			{
				if ((this._EMPNAME != value))
				{
					this._EMPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOI", DbType="Date")]
		public System.Nullable<System.DateTime> DOI
		{
			get
			{
				return this._DOI;
			}
			set
			{
				if ((this._DOI != value))
				{
					this._DOI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOE", DbType="Date")]
		public System.Nullable<System.DateTime> DOE
		{
			get
			{
				return this._DOE;
			}
			set
			{
				if ((this._DOE != value))
				{
					this._DOE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN1", DbType="VarChar(50)")]
		public string PLAN1
		{
			get
			{
				return this._PLAN1;
			}
			set
			{
				if ((this._PLAN1 != value))
				{
					this._PLAN1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREMIUM", DbType="VarChar(50)")]
		public string PREMIUM
		{
			get
			{
				return this._PREMIUM;
			}
			set
			{
				if ((this._PREMIUM != value))
				{
					this._PREMIUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_NAME", DbType="VarChar(50)")]
		public string AGENT_NAME
		{
			get
			{
				return this._AGENT_NAME;
			}
			set
			{
				if ((this._AGENT_NAME != value))
				{
					this._AGENT_NAME = value;
				}
			}
		}
	}
	
	public partial class sp_get_master_ZTR_VISAResult
	{
		
		private string _PERNR;
		
		private string _VINUM;
		
		private string _PASNUM;
		
		private string _EMPNAME;
		
		private string _COUNTRY;
		
		private System.Nullable<System.DateTime> _DOI;
		
		private System.Nullable<System.DateTime> _DOE;
		
		private string _VISA_TYPE;
		
		public sp_get_master_ZTR_VISAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(50)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VINUM", DbType="VarChar(50)")]
		public string VINUM
		{
			get
			{
				return this._VINUM;
			}
			set
			{
				if ((this._VINUM != value))
				{
					this._VINUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASNUM", DbType="VarChar(50)")]
		public string PASNUM
		{
			get
			{
				return this._PASNUM;
			}
			set
			{
				if ((this._PASNUM != value))
				{
					this._PASNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNAME", DbType="VarChar(50)")]
		public string EMPNAME
		{
			get
			{
				return this._EMPNAME;
			}
			set
			{
				if ((this._EMPNAME != value))
				{
					this._EMPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="VarChar(50)")]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this._COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOI", DbType="Date")]
		public System.Nullable<System.DateTime> DOI
		{
			get
			{
				return this._DOI;
			}
			set
			{
				if ((this._DOI != value))
				{
					this._DOI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOE", DbType="Date")]
		public System.Nullable<System.DateTime> DOE
		{
			get
			{
				return this._DOE;
			}
			set
			{
				if ((this._DOE != value))
				{
					this._DOE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISA_TYPE", DbType="VarChar(50)")]
		public string VISA_TYPE
		{
			get
			{
				return this._VISA_TYPE;
			}
			set
			{
				if ((this._VISA_TYPE != value))
				{
					this._VISA_TYPE = value;
				}
			}
		}
	}
	
	public partial class sp_get_master_ZTR_PASSPORTResult
	{
		
		private string _PERNR;
		
		private string _EMPNAME;
		
		private string _PASNUM;
		
		private System.Nullable<System.DateTime> _DOI;
		
		private System.Nullable<System.DateTime> _DOE;
		
		private string _PLISS;
		
		public sp_get_master_ZTR_PASSPORTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(50)")]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this._PERNR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNAME", DbType="VarChar(50)")]
		public string EMPNAME
		{
			get
			{
				return this._EMPNAME;
			}
			set
			{
				if ((this._EMPNAME != value))
				{
					this._EMPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASNUM", DbType="VarChar(50)")]
		public string PASNUM
		{
			get
			{
				return this._PASNUM;
			}
			set
			{
				if ((this._PASNUM != value))
				{
					this._PASNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOI", DbType="Date")]
		public System.Nullable<System.DateTime> DOI
		{
			get
			{
				return this._DOI;
			}
			set
			{
				if ((this._DOI != value))
				{
					this._DOI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOE", DbType="Date")]
		public System.Nullable<System.DateTime> DOE
		{
			get
			{
				return this._DOE;
			}
			set
			{
				if ((this._DOE != value))
				{
					this._DOE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLISS", DbType="VarChar(50)")]
		public string PLISS
		{
			get
			{
				return this._PLISS;
			}
			set
			{
				if ((this._PLISS != value))
				{
					this._PLISS = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_personal_ids_fullResult
	{
		
		private int _ID;
		
		private string _ICTYPE;
		
		private string _ICTXT;
		
		private string _ICNUM;
		
		private string _STATUS;
		
		private string _TransStatus;
		
		public sp_pi_get_personal_ids_fullResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTYPE", DbType="VarChar(2)")]
		public string ICTYPE
		{
			get
			{
				return this._ICTYPE;
			}
			set
			{
				if ((this._ICTYPE != value))
				{
					this._ICTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTXT", DbType="VarChar(30)")]
		public string ICTXT
		{
			get
			{
				return this._ICTXT;
			}
			set
			{
				if ((this._ICTXT != value))
				{
					this._ICTXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="VarChar(30)")]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this._ICNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransStatus", DbType="VarChar(20)")]
		public string TransStatus
		{
			get
			{
				return this._TransStatus;
			}
			set
			{
				if ((this._TransStatus != value))
				{
					this._TransStatus = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_personal_idsResult
	{
		
		private System.Nullable<long> _RowNumber;
		
		private int _ID;
		
		private string _ICTYPE;
		
		private string _ICTXT;
		
		private string _ICNUM;
		
		private System.Nullable<int> _RecordCnt;
		
		public sp_pi_get_personal_idsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNumber", DbType="BigInt")]
		public System.Nullable<long> RowNumber
		{
			get
			{
				return this._RowNumber;
			}
			set
			{
				if ((this._RowNumber != value))
				{
					this._RowNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTYPE", DbType="VarChar(2)")]
		public string ICTYPE
		{
			get
			{
				return this._ICTYPE;
			}
			set
			{
				if ((this._ICTYPE != value))
				{
					this._ICTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTXT", DbType="VarChar(30)")]
		public string ICTXT
		{
			get
			{
				return this._ICTXT;
			}
			set
			{
				if ((this._ICTXT != value))
				{
					this._ICTXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="VarChar(30)")]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this._ICNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordCnt", DbType="Int")]
		public System.Nullable<int> RecordCnt
		{
			get
			{
				return this._RecordCnt;
			}
			set
			{
				if ((this._RecordCnt != value))
				{
					this._RecordCnt = value;
				}
			}
		}
	}
	
	public partial class sp_pi_get_Personalidinfo_mailResult
	{
		
		private int _ID;
		
		private string _PKEY;
		
		private string _ICTYPE;
		
		private string _ICTXT;
		
		private string _ICNUM;
		
		public sp_pi_get_Personalidinfo_mailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKEY", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PKEY
		{
			get
			{
				return this._PKEY;
			}
			set
			{
				if ((this._PKEY != value))
				{
					this._PKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTYPE", DbType="VarChar(2)")]
		public string ICTYPE
		{
			get
			{
				return this._ICTYPE;
			}
			set
			{
				if ((this._ICTYPE != value))
				{
					this._ICTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICTXT", DbType="VarChar(30)")]
		public string ICTXT
		{
			get
			{
				return this._ICTXT;
			}
			set
			{
				if ((this._ICTXT != value))
				{
					this._ICTXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="VarChar(30)")]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this._ICNUM = value;
				}
			}
		}
	}
	
	public partial class sp_get_PERNRPANResult
	{
		
		private string _ICNUM;
		
		public sp_get_PERNRPANResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this._ICNUM = value;
				}
			}
		}
	}
	
	public partial class payc_Load_benefitsbased_onEmpidResult
	{
		
		private string _TEXT;
		
		private string _VALUE;
		
		public payc_Load_benefitsbased_onEmpidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEXT", DbType="NVarChar(128)")]
		public string TEXT
		{
			get
			{
				return this._TEXT;
			}
			set
			{
				if ((this._TEXT != value))
				{
					this._TEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="VarChar(100)")]
		public string VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this._VALUE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
