<?xml version="1.0" encoding="utf-8"?><Database Name="Paycompute_NewUIPRD" Class="masterdalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Paycompute_NewUIPRD;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iEmpPowerConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_master_load_states" Method="sp_master_load_states">
    <ElementType Name="sp_master_load_statesResult">
      <Column Name="LAND1" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="BLAND" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="BEZEI" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_member_types" Method="sp_master_load_member_types">
    <ElementType Name="sp_master_load_member_typesResult">
      <Column Name="SUBTY" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="Char(40)" CanBeNull="true" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_bank_types" Method="sp_master_load_bank_types">
    <ElementType Name="sp_master_load_bank_typesResult">
      <Column Name="SUBTY" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="STEXT" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_payment_currency" Method="sp_master_load_payment_currency">
    <ElementType Name="sp_master_load_payment_currencyResult">
      <Column Name="WAERS" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="LTEXT" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_payment_method" Method="sp_master_load_payment_method">
    <Parameter Name="LAND1" Parameter="lAND1" Type="System.String" DbType="VarChar(3)" />
    <ElementType Name="sp_master_load_payment_methodResult">
      <Column Name="LAND1" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="ZLSCH" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="TEXT1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_name_prefix_othertitle" Method="sp_master_load_name_prefix_othertitle">
    <ElementType Name="sp_master_load_name_prefix_othertitleResult">
      <Column Name="ART" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TTOUT" Type="System.String" DbType="Char(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_bank_keys" Method="sp_master_load_bank_keys">
    <Parameter Name="BANKS" Parameter="bANKS" Type="System.String" DbType="VarChar(3)" />
    <ElementType Name="sp_master_load_bank_keysResult">
      <Column Name="BANKS" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BANKL" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BANKA" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_language_dropdown" Method="sp_master_load_language_dropdown">
    <ElementType Name="sp_master_load_language_dropdownResult">
      <Column Name="SPRSL" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="SPTXT" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_religion" Method="sp_master_load_religion">
    <ElementType Name="sp_master_load_religionResult">
      <Column Name="KITXT" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="KTEXT" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_marital_status" Method="sp_master_load_marital_status">
    <ElementType Name="sp_master_load_marital_statusResult">
      <Column Name="FAMST" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="FTEXT" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_title" Method="sp_master_load_title">
    <ElementType Name="sp_master_load_titleResult">
      <Column Name="ANRED" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="ATEXT" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ANRLT" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_time_events" Method="sp_master_load_time_events">
    <ElementType Name="sp_master_load_time_eventsResult">
      <Column Name="DDTEXT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOMVALUE_L" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_travel_request_activities" Method="sp_master_load_travel_request_activities">
    <ElementType Name="sp_master_load_travel_request_activitiesResult">
      <Column Name="KZTKT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TKTXT" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_expenses_receipts" Method="sp_master_load_expenses_receipts">
    <ElementType Name="sp_master_load_expenses_receiptsResult">
      <Column Name="SPKZL" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="SPTXT" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_provider_category" Method="sp_master_load_provider_category">
    <ElementType Name="sp_master_load_provider_categoryResult">
      <Column Name="PROVIDER" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_trip_type_enterprise" Method="sp_master_load_trip_type_enterprise">
    <ElementType Name="sp_master_load_trip_type_enterpriseResult">
      <Column Name="BEREI" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TEXT25" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_trip_type_statutory" Method="sp_master_load_trip_type_statutory">
    <ElementType Name="sp_master_load_trip_type_statutoryResult">
      <Column Name="KZREA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RETXT" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_vehicle_class" Method="sp_master_load_vehicle_class">
    <ElementType Name="sp_master_load_vehicle_classResult">
      <Column Name="PKWKL" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="TEXT25" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_vehicle_type" Method="sp_master_load_vehicle_type">
    <ElementType Name="sp_master_load_vehicle_typeResult">
      <Column Name="KZPMF" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FZTXT" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_encashable_leaves" Method="sp_master_load_encashable_leaves">
    <ElementType Name="sp_master_load_encashable_leavesResult">
      <Column Name="MOAWB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AWART" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ATEXT" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ENCASHABLE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_property_type" Method="sp_master_load_property_type">
    <ElementType Name="sp_master_load_property_typeResult">
      <Column Name="type_id" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="type_value" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="type_name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_sub_type" Method="sp_master_load_sub_type">
    <ElementType Name="sp_master_load_sub_typeResult">
      <Column Name="TC" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="Char(40)" CanBeNull="true" />
      <Column Name="SUBTY" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_address_type" Method="sp_master_load_address_type">
    <ElementType Name="sp_master_load_address_typeResult">
      <Column Name="SUBTY" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="Char(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_slctd_country_states" Method="sp_master_load_slctd_country_states">
    <Parameter Name="LAND1" Parameter="lAND1" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_master_load_slctd_country_statesResult">
      <Column Name="BLAND" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="BEZEI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_personal_id_type" Method="sp_master_load_personal_id_type">
    <ElementType Name="sp_master_load_personal_id_typeResult">
      <Column Name="ICTYP" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ICTXT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_country_nationality" Method="sp_master_load_country_nationality">
    <ElementType Name="sp_master_load_country_nationalityResult">
      <Column Name="LAND1" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="LANDX" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NATIO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_costcenter" Method="sp_master_load_costcenter">
    <ElementType Name="sp_master_load_costcenterResult">
      <Column Name="CC_Text" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="KOSTL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LTEXT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_network" Method="sp_master_load_network">
    <Parameter Name="wbs" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_master_load_networkResult">
      <Column Name="AUFNR" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="KTEXT" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PSPEL" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_acttype" Method="sp_master_load_acttype">
    <Parameter Name="network" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="wbsid" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_master_load_acttypeResult">
      <Column Name="VORNR" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="LTXA1" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PROJN" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_Activities" Method="sp_get_Activities">
    <ElementType Name="sp_get_ActivitiesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AWART" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_CheckHR_Aqu" Method="usp_CheckHR_Aqu">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="STATUS" Parameter="sTATUS" Type="System.String" DbType="VarChar(5)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_master_load_att_abs_Leave" Method="sp_master_load_att_abs_Leave">
    <Parameter Name="TYPE" Parameter="tYPE" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="compCode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_master_load_att_abs_LeaveResult">
      <Column Name="MOABW" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AWART" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ATEXT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_att_abs" Method="sp_master_load_att_abs">
    <Parameter Name="cc" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_master_load_att_absResult">
      <Column Name="MOAWB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AWART" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ATEXT" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Company_Code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.payc_Get_Employee_Bday" Method="payc_Get_Employee_Bday">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ccode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="bt" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <ElementType Name="payc_Get_Employee_BdayResult">
      <Column Name="ENAME" Type="System.String" DbType="VarChar(154)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.payc_load_basedon_mainSearch" Method="payc_load_basedon_mainSearch">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="flg" Type="System.Int32" DbType="Int" />
    <ElementType Name="payc_load_basedon_mainSearchResult">
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_wbs" Method="sp_master_load_wbs">
    <Parameter Name="cc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="project" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_master_load_wbsResult">
      <Column Name="PSPNR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="POSID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_acty" Method="sp_master_load_acty">
    <Parameter Name="cc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="WBS" Parameter="wBS" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_master_load_actyResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activity" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_order" Method="sp_master_load_order">
    <Parameter Name="cc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="begda" Type="System.DateTime" DbType="Date" />
    <Parameter Name="endda" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_master_load_orderResult">
      <Column Name="PSPNR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PSPID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="POST1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Company_Code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Start_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="End_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Extn_Project_ID" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.payc_master_load_acty" Method="payc_master_load_acty">
    <Parameter Name="cc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="actytyp" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="WBS" Parameter="wBS" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="payc_master_load_actyResult">
      <Column Name="Countlst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activity" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_load_dashboard_Tile_update_details" Method="usp_load_dashboard_Tile_update_details">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="flg" Type="System.Int32" DbType="Int" />
    <Parameter Name="favrt" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="txt" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="valid" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_load_dashboard_Tile_details" Method="usp_load_dashboard_Tile_details">
    <Parameter Name="PERNR" Parameter="pERNR" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ccode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="flg" Type="System.Int32" DbType="Int" />
    <Parameter Name="favrt" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="usp_load_dashboard_Tile_detailsResult">
      <Column Name="PERNR" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="U_Tile_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="U_Tile_Path" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="U_Tile_icon" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_SubFunction" Method="sp_master_load_SubFunction">
    <Parameter Name="Requestor_Perner" Parameter="requestor_Perner" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_master_load_SubFunctionResult">
      <Column Name="BTEXT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_UnitofMeasurement" Method="sp_master_load_UnitofMeasurement">
    <Parameter Name="ItemNameId" Parameter="itemNameId" Type="System.String" DbType="Char(18)" />
    <ElementType Name="sp_master_load_UnitofMeasurementResult">
      <Column Name="MATNR" Type="System.String" DbType="Char(18)" CanBeNull="true" />
      <Column Name="MEINS" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_AllUnitofMeasurement" Method="sp_master_load_AllUnitofMeasurement">
    <ElementType Name="sp_master_load_AllUnitofMeasurementResult">
      <Column Name="ISOCODE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="ISOTXT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_Requestor_Region" Method="sp_master_load_Requestor_Region">
    <ElementType Name="sp_master_load_Requestor_RegionResult">
      <Column Name="EKGRP" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="EKNAM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_Region" Method="sp_master_load_Region">
    <ElementType Name="sp_master_load_RegionResult">
      <Column Name="REGION_ID" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="REGION_TEXT" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_Project" Method="sp_master_load_Project">
    <Parameter Name="createdby" Type="System.String" DbType="VarChar(8)" />
    <ElementType Name="sp_master_load_ProjectResult">
      <Column Name="WBSID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WBS" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_PrjMangr_forPrjCode" Method="sp_master_load_PrjMangr_forPrjCode">
    <Parameter Name="posid" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_master_load_PrjMangr_forPrjCodeResult">
      <Column Name="VERNR" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="VERNA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_MISAB" Method="sp_master_load_MISAB">
    <Parameter Name="Grp_Cid" Parameter="grp_Cid" Type="System.String" DbType="VarChar(4)" />
    <ElementType Name="sp_master_load_MISABResult">
      <Column Name="CID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="A_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="B_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_MISC" Method="sp_master_load_MISC">
    <ElementType Name="sp_master_load_MISCResult">
      <Column Name="CID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="C_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_MainFunction" Method="sp_master_load_MainFunction">
    <Parameter Name="Requestor_Perner" Parameter="requestor_Perner" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_master_load_MainFunctionResult">
      <Column Name="FUNC_AREA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_CategoryItem_Desc" Method="sp_master_load_CategoryItem_Desc">
    <ElementType Name="sp_master_load_CategoryItem_DescResult">
      <Column Name="MATNR" Type="System.String" DbType="Char(18)" CanBeNull="true" />
      <Column Name="MAKTX" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_ExpenseType_travel" Method="sp_master_load_ExpenseType_travel">
    <Parameter Name="triptype" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="pernr" Type="System.String" DbType="VarChar(8)" />
    <ElementType Name="sp_master_load_ExpenseType_travelResult">
      <Column Name="SPKZL" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="SPTXT" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_ExpenseType" Method="sp_master_load_ExpenseType">
    <Parameter Name="task" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="sp_master_load_ExpenseTypeResult">
      <Column Name="LGART" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="LGTXT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_ProjectCode" Method="sp_master_load_ProjectCode">
    <ElementType Name="sp_master_load_ProjectCodeResult">
      <Column Name="POSID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="POST1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_master_load_BusinessUnit" Method="sp_master_load_BusinessUnit">
    <Parameter Name="Entity" Parameter="entity" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_master_load_BusinessUnitResult">
      <Column Name="SPART" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="VTEXT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_BillShipToAddress" Method="sp_get_BillShipToAddress">
    <ElementType Name="sp_get_BillShipToAddressResult">
      <Column Name="WERKS" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="NAME1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_region_name_s" Method="sp_get_region_name_s">
    <Parameter Name="LAND1" Parameter="lAND1" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="sp_get_region_name_sResult">
      <Column Name="RGION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEXT25" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_region_name" Method="sp_get_region_name">
    <ElementType Name="sp_get_region_nameResult">
      <Column Name="RGION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEXT25" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>